### PR TITLE
[`data_loader`] Optionally also propagate set_epoch to batch sampler

### PR DESCRIPTION
**Pull request by tomaarsen**
# What does this PR do?

When training with the `transformers` Trainer or related (Sentence Transformers, SpanMarker, SetFit, etc.), `set_epoch` is called on the dataloader. This is propagated down to the `dataloader.batch_sampler.sampler` if that has a `set_epoch` , but not to `dataloader.batch_sampler`.

This prevents epoch-specific generator seeding in custom batch samplers, such as the ones that are common in Sentence Transformers: https://sbert.net/docs/package_reference/sentence_transformer/sampler.html

See also https://github.com/UKPLab/sentence-transformers/issues/3069 by @antigregory which showed that `set_epoch` in my Batch Samplers is not called like I expected them to be.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

@muellerzr (p.s. get better soon!)

- Tom Aarsen

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Thanks for propagating! Can you confirm it fixes your issue? (If so, we either should add a test, or add `SentenceTransformer` test subsets into accelerate)

**Comment by tomaarsen** [comment]
> Can you confirm it fixes your issue?

It does indeed. I think I can write a test to go alongside this PR.

- Tom Aarsen

**Comment by tomaarsen** [comment]
This test roughly mirrors my use case and should act as an effective test to make sure ST should work. Feel free to update it if e.g. you don't normally use `Accelerator` in the `data_loader` tests.

- Tom Aarsen

**Review by muellerzr — COMMENTED** [review]
Thanks for adding!

**Pull request merged**
