### PR TITLE
Deepspeed integration for XPU/ccl

### PR DESCRIPTION
**Pull request by abhilash1910**
Deepspeed has exposed  support to different backends .So for using deepspeed through accelerate on xpus, the ccl backend is required. Also mpich support was added in deepspeed before (by me) so that can be added too for multinode. 
@sgugger @muellerzr

### CODE REVIEW

**Comment by sgugger** [comment]
cc @pacman100

**Comment by abhilash1910** [comment]
@pacman100  could you take a look ? Thanks

**Comment by abhilash1910** [comment]
@sgugger  any updates/reviews on this PR ? Thanks

**Comment by sgugger** [comment]
Still waiting for @pacman100 to take a look.

**Review by pacman100 — APPROVED** [review]
Thank you @abhilash1910 for adding support for XPU when using DeepSpeed. LGTM!

**Comment by sgugger** [comment]
@pacman100 You will need to merge the PR if you are happy with it ;-)

**Pull request merged**
