### PR TITLE
MLU devices : Checks if mlu is available via an cndev-based check which won't trigger the drivers and leave mlu

### PR DESCRIPTION
**Pull request by huismiling**
# What does this PR do?

MLU devices : Checks if mlu is available via an cndev-based check which won't trigger the drivers and leave mlu

Check devices(cuda and mlu) is available with `patch_environment` . 

Move `clear_environment` and `patch_environment` into `src/accelerate/utils/environment.py` to avoid circular import .

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by huismiling** [comment]
@BenjaminBossan @muellerzr 
Previous PR https://github.com/huggingface/accelerate/pull/3057 is closed.
Sorry for taking so long time to fix circular import. 
`clear_environment `and `patch_environment` are moved into [src/accelerate/utils/environment.py](https://github.com/huismiling/accelerate/blob/main/src/accelerate/utils/environment.py) .

**Review by muellerzr — APPROVED** [review]
Thanks! Makes sense that we do the realignment here of things & how they ended up.

**Review by BenjaminBossan — APPROVED** [review]
Thanks for coming back to this PR, LGTM.

Short question for @muellerzr: We should be fine with the functions no longer being importable from `accelerate.utils.other` because users should always import from the higher level, right?

**Comment by muellerzr** [comment]
Yep exactly. We can add a deprecation warning here but we've never advertised it in that way at that import level so I think we should be fine.

**Comment by BenjaminBossan** [comment]
Okay, great, just wanted to be sure. This PR is good to be merged from my point of view.

**Pull request merged**
