### PR TITLE
Fix batch_size sanity check in `prepare_data_loader`

### LINKED ISSUE #2285: `accelerator.prepare(dataloader)` sanity check fails when `batch_sampler` is given and `split_batches` is `True`
### System Info

```Shell
Ubuntu 20.04, Python 3.10, accelerate 0.25.0, torch 2.1.2
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I am attempting to manually pass a `BatchSampler` to `DataLoader` while enabling the `split_batches` option.

```
from accelerate import Accelerator
from torch.utils.data import Dataset, DataLoader, BatchSampler, RandomSampler


class SimpleDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __getitem__(self, index) -> dict:
        return self.data[index]

    def __len__(self):
        return len(self.data)

accelerator = Accelerator(split_batches=True)

dataset = SimpleDataset([0, 1, 2, 3, 4])
batch_sampler = BatchSampler(RandomSampler(dataset), 2, True)
loader = DataLoader(dataset, batch_sampler=batch_sampler)
accelerator.prepare(loader)
```

But it fails at the sanity check of https://github.com/huggingface/accelerate/blob/ceb7c699bc36bdb3bbf32cceaaca2d1ceaf62dae/src/accelerate/data_loader.py#L827

```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    accelerator.prepare(loader)
  File "/envs/flash/lib/python3.10/site-packages/accelerate/accelerator.py", line 1213, in prepare
    result = tuple(
  File "/envs/flash/lib/python3.10/site-packages/accelerate/accelerator.py", line 1214, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/envs/flash/lib/python3.10/site-packages/accelerate/accelerator.py", line 1092, in _prepare_one
    return self.prepare_data_loader(obj, device_placement=device_placement)
  File "/envs/flash/lib/python3.10/site-packages/accelerate/accelerator.py", line 1788, in prepare_data_loader
    prepared_data_loader = prepare_data_loader(
  File "/envs/flash/lib/python3.10/site-packages/accelerate/data_loader.py", line 820, in prepare_data_loader
    if split_batches and dataloader.batch_size > 1 and dataloader.batch_size % num_processes != 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

The `dataloader.batch_size` is set to `None` in `dataloader.__init__` if `batch_sampler` is given, see https://github.com/pytorch/pytorch/blob/f6dfbffb3bb46ada6fe66b5da4f989f9d4d69b3c/torch/utils/data/dataloader.py#L336
```
        if batch_sampler is not None:
            # auto_collation with custom batch_sampler
            if batch_size != 1 or shuffle or sampler is not None or drop_last:
                raise ValueError('batch_sampler option is mutually exclusive '
                                 'with batch_size, shuffle, sampler, and '
                                 'drop_last')
            batch_size = None
            drop_last = False
```

### Expected behavior

Pass the check.

### PR DESCRIPTION
**Pull request by izhx**
# What does this PR do?

Fixes #2285

The `dataloader.batch_size` is set to `None` in `DataLoader.__init__` if `batch_sampler` is given.

I made the `split_batches` sanity check depend on `dataloader.batch_sampler.batch_size` if `dataloader.batch_size` is `None`

I have pass passed `pytest tests/test_data_loader.py`, `make style` and `make quality` on my linux GPU server.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@muellerzr

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Thanks! This indeed seems like a better way to check for this

**Review by BenjaminBossan — APPROVED** [review]
Thanks for this clean fix.

**Comment by stas00** [comment]
Unfortunately, this broke Megatron DL :(

```
  File "/data/env/lib/repos/retro-llama/tr041-dawn-llama/core/dawn/dawn/train/common/trainer.py", line 602, in prepare_register
   ) = self.accelerator.prepare(
 File "/exp/clm/tr041-dawn-llama/CONDA_ENV_NAME/lib/python3.9/site-packages/accelerate/accelerator.py", line 1219, in prepare
   result = self._prepare_deepspeed(*args)
 File "/exp/clm/tr041-dawn-llama/CONDA_ENV_NAME/lib/python3.9/site-packages/accelerate/accelerator.py", line 1424, in _prepare_deepspeed
   result = [
 File "/exp/clm/tr041-dawn-llama/CONDA_ENV_NAME/lib/python3.9/site-packages/accelerate/accelerator.py", line 1425, in <listcomp>
   self._prepare_one(obj, first_pass=True) if isinstance(obj, torch.utils.data.DataLoader) else obj
 File "/exp/clm/tr041-dawn-llama/CONDA_ENV_NAME/lib/python3.9/site-packages/accelerate/accelerator.py", line 1102, in _prepare_one
   return self.prepare_data_loader(obj, device_placement=device_placement)
 File "/exp/clm/tr041-dawn-llama/CONDA_ENV_NAME/lib/python3.9/site-packages/accelerate/accelerator.py", line 1846, in prepare_data_loader
   prepared_data_loader = prepare_data_loader(
 File "/exp/clm/tr041-dawn-llama/CONDA_ENV_NAME/lib/python3.9/site-packages/accelerate/data_loader.py", line 840, in prepare_data_loader
   batch_size = dataloader.batch_size if dataloader.batch_size is not None else dataloader.batch_sampler.batch_size
[32:5]:AttributeError: 'MegatronPretrainingSampler' object has no attribute 'batch_size'

```
I don't see any API in pytorch that suggests that `.batch_size` should be in the `Sampler` class

https://pytorch.org/docs/stable/_modules/torch/utils/data/sampler.html#SequentialSampler

and you can see Megatron Sampler uses `.micro-batch_size`

https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/data/data_samplers.py#L57y

**Comment by izhx** [comment]
You are right. I am working on improving this check.

For a quick fix, you can comment out these lines if `split_batches` is not needed.

**Comment by izhx** [comment]
`BatchSampler` has `batch_size`. https://pytorch.org/docs/stable/data.html#torch.utils.data.BatchSampler

In your case, It seems that `MegatronPretrainingSampler ` does not follow the design of `BatchSampler`.

However, a more complex check logic is indeed needed.

**Comment by stas00** [comment]
`MegatronPretrainingSampler` isn't a subclass of `BatchSampler` - perhaps that's why it didn't follow the same conventions?

Note there is another sampler in there as well https://github.com/NVIDIA/Megatron-LM/blob/a22f6723622bd09de60ff88e8dcd151c3de958c9/megatron/data/data_samplers.py#L129

**Comment by izhx** [comment]
> `MegatronPretrainingSampler` isn't a subclass of `BatchSampler` - perhaps that's why it didn't follow the same conventions?
> 
> Note there is another sampler in there as well https://github.com/NVIDIA/Megatron-LM/blob/a22f6723622bd09de60ff88e8dcd151c3de958c9/megatron/data/data_samplers.py#L129

Yes, but it is set as the `batch_sampler` of the dataloader, that's why this line of code crashed.
It is used as a `batch_sampler`, but it does not inherit `BatchSampler` or follow the conventions.

That's a bit confusing. However, I now seem to understand why there were some strange lines https://github.com/huggingface/accelerate/blob/ceb7c699bc36bdb3bbf32cceaaca2d1ceaf62dae/src/accelerate/data_loader.py#L838

**Comment by stas00** [comment]
That's totally understandable. The other option is to perhaps ask Meg-LM folks to fix it or send a PR?

While you're improving that code if you feel inspired probably also fix that 2 lines of initing `sampler_is_batch_sampler` - the first one can be removed, IMHO:
https://github.com/huggingface/accelerate/blob/31fd2b1ad6b9c1cd1480568399a311b3caaf62dc/src/accelerate/data_loader.py#L850C1-L852C76

**Pull request merged**
