### PR TITLE
update Megatron-LM plugin code to version 0.8.0 or higher.

### PR DESCRIPTION
**Pull request by eljandoubi**
# What does this PR do?
I have adapted the Megatron-LM plugin code to version 0.8.0 or higher.
Same setup as before, but now Megatron-LM is using `core_r0.8.0`.

## Who can review?

- Core parts of the library: @muellerzr @BenjaminBossan @SunMarc+

### CODE REVIEW

**Review by muellerzr — COMMENTED** [review]
Does the old code work from 0.5 -> 0.7.0? I'd rather see `if`/`else` checks rather than fully always bump the user up to the latest.

**Review by muellerzr — APPROVED** [review]
This is fine I suppose then. Thanks :)

**Comment by muellerzr** [comment]
(Failing tests are unrelated, python update)

**Comment by eljandoubi** [comment]
Megatron-LM 0.9.0 is out. I believe the plugin is still functional. Can you confirm?

**Pull request merged**
