### PR TITLE
Dockerfile consolidation / Local development experience

### PR DESCRIPTION
**Pull request by dbpprt**
Inspired by the issues with Visual Studio Code Dev Containers, I reworked both the **Dockerfiles** and the **devcontainer.json**.

### Major Changes in here:
- Both GPU and CPU images are combined into a single image using ARGS
- The CPU image uses the same mechanism as the GPU image (potentially a breaking change?)
- The ARGS allow the container image to be customized, e.g. for people wanting to use the SageMaker integration (installing additional dependencies for development)

This change requires additional parameters to be set in CI/CD to pass the required parameters:

```yaml
build-args: |
    BASE_REPOSITORY=https://github.com/huggingface/accelerate#egg=accelerate[testing,test_trackers]
    PYTHON_VERSION=3.7.3
    PYTORCH_COMPUTE_PLATFORM=cpu/cu113
    BASE_IMAGE=nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04 / ubuntu:20.04
``` 

### Advantages:
- No need for different Dockerfiles
- Version configurable, potentially through CI/CD or from an additional file
- Nice development experience when using Dev Containers

### Potential disadvantes:
- CPU container uses a different base image and Conda
- CPU container might be larger? Potentially a different base image works, too.

*Unless you know better :)*

Happy to get some feedback.

### CODE REVIEW

**Comment by dennisbappert** [comment]
The **devcontainer.json** uses `ARGS` to define the target development environment.

```json
"build": {
      "dockerfile": "../Dockerfile",
      "args": {
        "BASE_REPOSITORY": "https://github.com/huggingface/accelerate#egg=accelerate[testing,test_trackers]",
        "PYTHON_VERSION": "3.7.3",
        
        // ACTION NEEDED: uncomment if you have a local GPU
        // "PYTORCH_COMPUTE_PLATFORM": "cu113",
        // ACTION_NEEDED: uncomment if you want to use a CPU only image
        "PYTORCH_COMPUTE_PLATFORM": "cpu",
        
        // ACTION NEEDED: uncomment if you have a local GPU
        // "BASE_IMAGE": "nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04",
        // ACTION_NEEDED: uncomment if you want to use a CPU only image
        "BASE_IMAGE": "ubuntu:20.04",
        
        // ACTION NEEDED: uncomment if you plan to use Amazon SageMaker local mode
        // "INSTALL_DOCKER": "1",
        // "INSTALL_AWS_CLI": "1",
        // "INSTALL_DOCKER_COMPOSE_V1": "1"
      }
    },
```

**Comment by Chris-hughes10** [comment]
Of course it depends on how the Hugging Face guys are using the Dockerfiles, and how willing they are to adapt any processes, but from my perspective, this is great work!

**Comment by sgugger** [comment]
@muellerzr Could you have a look here? Thanks!

**Comment by muellerzr** [comment]
This is indeed a breaking change and the dockerfile being built is completely different than the original one. The ones in Accelerate currently are designed to be minimal based on solely dev-install and are used for testing as well. Here we've added `ipython` and `jupyter`. 

The main part I mostly care about is:

1. How big is the newly created docker images themselves? The CPU image is designed to be extremely small and minimal, and the GPU image (relatively) small as well
2. If we then do go with this new docker image, the docker workflow needs to be changed *before* we can merge this. [Workflow A](https://github.com/huggingface/accelerate/blob/main/.github/workflows/build_docker_images.yml), [Workflow B](https://github.com/huggingface/accelerate/blob/main/.github/workflows/build-docker-images-release.yml)

Thanks for your work on this though! Just need to make sure these changes don't drastically increase the image sizes, we likely will need to modify those workflows to include at least a few of the optional tags (esp Sagemaker), and ensure those get released as well on our release and nightly schedules. Let me know if there are any questions on any of this :)

**Comment by dennisbappert** [comment]
Thanks @muellerzr for your feedback. This PR focuses on streamlining the experience between both images, which means: same base, both using conda, etc. They behave exactly the same, the core difference just being GPU support, which allows reproducibility between both. 

The image sizes using the proposed `Dockerfile` in this PR:
```bash
docker build . --build-arg PYTORCH_COMPUTE_PLATFORM=cpu --build-arg BASE_IMAGE=ubuntu:20.04 --build-arg BASE_REPOSITORY=https://github.com/huggingface/accelerate#egg=accelerate[testing,test_trackers] --build-arg PYTHON_VERSION=3.7.3 -t accelerate:cpu
docker inspect -f "{{ .Size }}" accelerate:cpu | numfmt --to=si
> 3.3G

docker build . --build-arg PYTORCH_COMPUTE_PLATFORM=gpu --build-arg BASE_IMAGE=nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04 --build-arg BASE_REPOSITORY=https://github.com/huggingface/accelerate#egg=accelerate[testing,test_trackers] --build-arg PYTHON_VERSION=3.7.3 -t accelerate:gpu
docker inspect -f "{{ .Size }}" accelerate:gpu | numfmt --to=si
> 13G
```

Current images:
```bash
docker pull huggingface/accelerate-cpu
docker inspect -f "{{ .Size }}" huggingface/accelerate-cpu:latest | numfmt --to=si
> 1.7G

docker pull huggingface/accelerate-gpu
docker inspect -f "{{ .Size }}" huggingface/accelerate-gpu:latest | numfmt --to=si
> 13G
```
*Note: all sizes are uncompressed!*

The current `Dockerfiles` have different approaches in handling their Python version, `gpu` uses hardcoded 3.7.3 (lacking many security updates), whereas `cpu` takes the latest available 3.7 release.

They are currently not much optimized for size, rather than reproducibility. If the image size is a concern, I can try to optimize the sizes a bit for the CPU image, in order to get them comparable.

**Comment by dbpprt** [comment]
Do you have any feedback on the proposed changes?

**Pull request closed without merging**
