### PR TITLE
Add ability to use SageMaker FileSystemInput for scaling training jobs using EFS and FSx

### PR DESCRIPTION
**Pull request by YashalShakti**
Add the ability to use FileSystemInput by specifying a dictionary in sagemaker_inputs. This is needed for using EFS or FSx on SageMaker.

https://aws.amazon.com/blogs/machine-learning/speed-up-training-on-amazon-sagemaker-using-amazon-efs-or-amazon-fsx-for-lustre-file-systems/

Testing
Tested submitting a SageMaker job with SageMaker inputs data .tsv file with the following format
[sample_fsx_accelerate_sagemaker.tsv](https://github.com/huggingface/accelerate/files/11644272/sample_fsx_accelerate._sagemaker.txt)

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
cc @philschmid

**Comment by philschmid** [comment]
@YashalShakti are you sure this works? Accelerate is currently not supporting VPC (subnet, security group) configurations ([see](https://github.com/huggingface/accelerate/blob/16ca01feeaf59ff3d67fb6328c04628e31f1fe72/src/accelerate/utils/launch.py#L447))

Can you please share your accelerate config and exact code you used?

**Comment by YashalShakti** [comment]
It is possible to pass VPC config to [additional args](https://github.com/huggingface/accelerate/blob/16ca01feeaf59ff3d67fb6328c04628e31f1fe72/src/accelerate/utils/launch.py#L466)

This is roughly the config that I used.
```
base_job_name: accelerate-sagemaker-1
compute_environment: AMAZON_SAGEMAKER
dynamo_config: {}
ec2_instance_type: ml.p3dn.24xlarge
distributed_type: 'NO'
gpu_ids: all
iam_role_name: arn:aws:iam::123:role/SAGEMAKER
image_uri: null
mixed_precision: fp16
num_machines: 1
profile: default
py_version: py38
pytorch_version: 1.10.2
region: us-west-2
transformers_version: 4.17.0
use_cpu: false
sagemaker_inputs_file: image_data.tsv
additional_args:
  security_group_ids: ["sg-xx", "sg-yy"]
  subnets: ["subnet-xyz"]
```

I will try to run a public example using EFS/FSX and try to share.

**Comment by YashalShakti** [comment]
# Example Script and Envs to run Accelerate locally, on SageMaker using S3 inputs, and on SageMaker using FSx inputs.

```python

import argparse
import os
from glob import glob
from accelerate import Accelerator
from accelerate.logging import get_logger

logger = get_logger(__name__)


def run_sample():
    parser = argparse.ArgumentParser(description="Simple example of a training script.")
    parser.add_argument(
        "--input_dir",
        type=str,
        default=os.environ.get("SM_CHANNEL_INPUT_DIR"),
        required=False)
    args = parser.parse_args()

    accelerator = Accelerator()
    print("Running accelerate")
    print(glob(os.path.join(args.input_dir, "*")))


if __name__ == "__main__":
    run_sample()
```

---

# Run locally

## Config - local.env

```
compute_environment: LOCAL_MACHINE
distributed_type: 'NO'
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

## Run

```shell
accelerate launch --config_file local.env sagemaker_accelerate.py --input_dir /

Running accelerate
['/dev', '/etc', '/local', '/proc', '/run', '/sys', '/tmp', '/var', '/usr', '/bin', '/sbin', '/lib', '/lib64', '/boot', '/home', '/media', '/mnt', '/opt']
```

---

# Run on SageMaker using S3

## Config - sagemaker_s3.env

```
base_job_name: accelerate-sagemaker-1
compute_environment: AMAZON_SAGEMAKER
distributed_type: 'NO'
ec2_instance_type: ml.p3.2xlarge
gpu_ids: all
iam_role_name: arn:aws:iam::XXXXXXXXXXXX:role/SAGEMAKER_XXXXXXX
mixed_precision: 'no'
num_machines: 1
profile: default
py_version: py38
pytorch_version: 1.10.2
region: us-west-2
sagemaker_inputs_file: sagemaker_s3.tsv
transformers_version: 4.17.0
use_cpu: false
```

## Input TSV file
```tsv
channel_name    data_location
INPUT_DIR       s3://XXXXXXXXXXXX/XXXXXXXXXXXX/
```
## Run

```shell
accelerate launch --config_file sagemaker_s3.env sagemaker_accelerate.py 


Configuring Amazon SageMaker environment
Converting Arguments to Hyperparameters
Loading SageMaker Inputs from sagemaker_s3.tsv file
Loaded SageMaker Inputs: {'INPUT_DIR': 's3://XXXXXXXXXXXX/XXXXXXXXXXXX/'}
Creating Estimator
Using provided s3_resource
INFO:sagemaker.image_uris:image_uri is not presented, retrieving image_uri based on instance_type, framework etc.
INFO:sagemaker:Creating training-job with name: accelerate-sagemaker-1-XXXXXXXXXXXX
2023-06-13 01:40:51 Starting - Starting the training job...
2023-06-13 01:41:19 Starting - Preparing the instances for training.........
2023-06-13 01:42:49 Downloading - Downloading input data
2023-06-13 01:42:49 Training - Downloading the training image.....................
2023-06-13 01:45:55 Training - Training image download completed. Training in progress
...
Running accelerate
['/opt/ml/input/data/INPUT_DIR/XXXXXXXXXXXX']
2023-06-13 01:46:23,275 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2023-06-13 01:46:23,275 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 0 from exiting process.
2023-06-13 01:46:23,275 sagemaker-training-toolkit INFO     Reporting training SUCCESS
```

# Run on SageMaker using FSX

## Config - sagemaker_fsx.env
```
base_job_name: accelerate-sagemaker-1
compute_environment: AMAZON_SAGEMAKER
distributed_type: 'NO'
ec2_instance_type: ml.p3.2xlarge
gpu_ids: all
iam_role_name: arn:aws:iam::XXXXXXXXXXXX:role/SAGEMAKER_XXXXXXXXXXXX
mixed_precision: 'no'
num_machines: 1
profile: default
py_version: py38
pytorch_version: 1.10.2
region: us-west-2
sagemaker_inputs_file: sagemaker_fsx.tsv
transformers_version: 4.17.0
use_cpu: false
additional_args:
  security_group_ids: ["sg-XXXXXXXXXXXX"]
  subnets: ["subnet-XXXXXXXXXXXX"]
```

## Input TSV file - sagemaker_fsx.tsv
```tsv
channel_name    data_location
INPUT_DIR       {"file_system_id": "fs-XXXXXXXXXXXX", "file_system_type": "FSxLustre", "directory_path": "/s98YXYX/XXXXXXXXXXXX/XXXXXXXXXXXX", "file_system_access_mode": "rw"}
```

## Run

```shell
accelerate launch --config_file sagemaker_fsx.env sagemaker_accelerate.py 

Configuring Amazon SageMaker environment
Converting Arguments to Hyperparameters
Loading SageMaker Inputs from sagemaker_fsx.tsv file
Loaded SageMaker Inputs: {'INPUT_DIR': '{"file_system_id": "fs-XXXXXXXXXXXX", "file_system_type": "FSxLustre", "directory_path": "/s98YXYX/XXXXXXXXXXXX/XXXXXXXXXXXX", "file_system_access_mode": "rw"}'}
Creating Estimator
Using provided s3_resource
INFO:sagemaker.image_uris:image_uri is not presented, retrieving image_uri based on instance_type, framework etc.
INFO:sagemaker:Creating training-job with name: accelerate-sagemaker-1-XXXXXXXXXXXX
2023-06-13 04:19:56 Starting - Starting the training job...
2023-06-13 04:20:23 Starting - Preparing the instances for training......
2023-06-13 04:21:25 Downloading - Downloading input data...
2023-06-13 04:21:40 Training - Downloading the training image........................
2023-06-13 04:25:36 Training - Training image download completed. Training in progress..bash: cannot set terminal process group 
...
Invoking script with the following command:
/opt/conda/bin/python3.8 sagemaker_accelerate.py
Running accelerate
['/opt/ml/input/data/XXXXXXXXXXXX']
2023-06-13 04:26:08,414 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2023-06-13 04:26:08,414 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 0 from exiting process.
2023-06-13 04:26:08,415 sagemaker-training-toolkit INFO     Reporting training SUCCESS

2023-06-13 04:26:18 Uploading - Uploading generated training model
2023-06-13 04:26:18 Completed - Training job completed
Training seconds: 292
Billable seconds: 292
```

**Pull request closed without merging**
