### PR TITLE
fix fstr format

### PR DESCRIPTION
**Pull request by Jintao-Huang**
# What does this PR do?

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

@muellerzr

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Nice! Thanks for doing this :)

**Comment by muellerzr** [comment]
@Jintao-Huang can you do `pip install -e .[quality]` + `make style; make quality`? That’ll fix up the quality check

**Comment by Jintao-Huang** [comment]
Hello, I have fixed the code quality issues. 😊

**Review by muellerzr — APPROVED** [review]
Fantastic! Thanks a bunch!

**Pull request merged**
