### PR TITLE
[Refactor] Refactor send_to_device to treat tensor-like first

### LINKED ISSUE #2405: Doesn't work with new PyTorch TensorDict
### System Info

```Shell
`Accelerate` version: 0.26.1
- Platform: Linux-5.19.0-45-generic-x86_64-with-glibc2.31
- Python version: 3.9.16
- Numpy version: 1.23.4
- PyTorch version (GPU?): 2.2.0+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 88.38 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

1. Use a TensorDict as the dataset passed into a PyTorch dataloader. For example, see the PyTorch example here: https://pytorch.org/tensordict/tutorials/data_fashion.html
2. Use accelerate to `accelerator.prepare` the dataloader.
3. Try to load batches from the prepared dataloader.

When I did this, I get the following error: 
```
ValueError: batch size was not specified when creating the TensorDict instance and it could not be retrieved from source.
```

This happens when Accelerate is putting the tensor on the right device. It seems to lose track of its batch_size attribute in the process. When I got rid of accelerator.prepare on my dataset (which is fine for now cause I'm training on 1 GPU) this error went away.

### Expected behavior

Expected behavior: it successfully returns batches from the dataloader.

### PR DESCRIPTION
**Pull request by vmoens**
# What does this PR do?

I propose to reorder `send_to_device` to directly call `to` if it's available, which will make it possible to use `TensorDict` OOB.
The function should be slightly faster too because you presumably have more tensors than containers in the structures send to `send_to_device` (so the new implementation will result in fewer checks which are known to introduce overhead in python).

Fixes #2405 

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [x] Did you write any new necessary tests?

## Who can review?

- Command Line Interface: @muellerzr

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Thanks for the refactor! Indeed not having to check and just go should make things quite a bit faster :)

**Comment by muellerzr** [comment]
@vmoens can you solve the conflicts and then we can merge this?

**Comment by vmoens** [comment]
This should work!

**Comment by muellerzr** [comment]
Great! Thanks for this. Let's keep an eye on `main` to make sure nothing fails on our single and multi-GPU CI's after merging (and these tests pass here)

**Pull request merged**
