### PR TITLE
device agnostic testing for hooks&utils&big_modeling

### PR DESCRIPTION
**Pull request by statelesshz**
# What does this PR do?

part of https://github.com/huggingface/accelerate/pull/2602#issue-2217828783

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by statelesshz** [comment]
- test results with npu
 ```text
=
(lynn) [root@localhost accelerate]# RUN_SLOW=1 python -m pytest -v tests/test_big_modeling.py
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.8.19, pytest-8.1.1, pluggy-1.4.0 -- /root/miniconda3/envs/lynn/bin/python
cachedir: .pytest_cache
rootdir: /home/lynn/accelerate
configfile: pyproject.toml
collected 32 items

tests/test_big_modeling.py::BigModelingTester::test_cpu_offload PASSED                                                                                                                                      [  3%]
tests/test_big_modeling.py::BigModelingTester::test_cpu_offload_gpt2 PASSED                                                                                                                                 [  6%]
tests/test_big_modeling.py::BigModelingTester::test_cpu_offload_with_hook PASSED                                                                                                                            [  9%]
tests/test_big_modeling.py::BigModelingTester::test_cpu_offload_with_unused_submodules PASSED                                                                                                               [ 12%]
tests/test_big_modeling.py::BigModelingTester::test_dipatch_model_fp4_simple SKIPPED (test requires the bitsandbytes library)                                                                               [ 15%]
tests/test_big_modeling.py::BigModelingTester::test_disk_offload PASSED                                                                                                                                     [ 18%]
tests/test_big_modeling.py::BigModelingTester::test_disk_offload_gpt2 PASSED                                                                                                                                [ 21%]
tests/test_big_modeling.py::BigModelingTester::test_disk_offload_with_unused_submodules PASSED                                                                                                              [ 25%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model PASSED                                                                                                                                   [ 28%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_bnb SKIPPED (test requires the bitsandbytes library)                                                                                     [ 31%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_copy PASSED                                                                                                                              [ 34%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_force_hooks PASSED                                                                                                                       [ 37%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_gpt2_on_two_devices PASSED                                                                                                               [ 40%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_int8_simple SKIPPED (test requires the bitsandbytes library)                                                                             [ 43%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_move_model_warning SKIPPED (test requires multiple GPUs)                                                                                 [ 46%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_move_offloaded_model PASSED                                                                                                              [ 50%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_mps SKIPPED (test requires a `mps` backend support in `torch`)                                                                           [ 53%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_multi_devices PASSED                                                                                                                     [ 56%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_tied_weights PASSED                                                                                                                      [ 59%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_tied_weights_memory SKIPPED (test requires multiple GPUs)                                                                                [ 62%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_tied_weights_memory_with_nested_offload_cpu SKIPPED (test requires a GPU)                                                                [ 65%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_tied_weights_memory_with_nested_offload_disk SKIPPED (test requires a GPU)                                                               [ 68%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_with_non_persistent_buffers PASSED                                                                                                       [ 71%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_with_unused_submodules PASSED                                                                                                            [ 75%]
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_with_unused_submodules_multi_device PASSED                                                                                               [ 78%]
tests/test_big_modeling.py::BigModelingTester::test_init_empty_weights PASSED                                                                                                                               [ 81%]
tests/test_big_modeling.py::BigModelingTester::test_init_empty_weights_very_large_model PASSED                                                                                                              [ 84%]
tests/test_big_modeling.py::BigModelingTester::test_init_on_device_cuda PASSED                                                                                                                              [ 87%]
tests/test_big_modeling.py::BigModelingTester::test_load_checkpoint_and_dispatch PASSED                                                                                                                     [ 90%]
tests/test_big_modeling.py::BigModelingTester::test_load_checkpoint_and_dispatch_multi_device PASSED                                                                                                        [ 93%]
tests/test_big_modeling.py::BigModelingTester::test_load_checkpoint_and_dispatch_multi_device_with_unused_submodules PASSED                                                                                 [ 96%]
tests/test_big_modeling.py::BigModelingTester::test_load_checkpoint_and_dispatch_with_unused_submodules PASSED                                                                                              [100%]

================================================================================================ warnings summary =================================================================================================
../../../root/miniconda3/envs/lynn/lib/python3.8/site-packages/torch_npu/dynamo/torchair/__init__.py:3
  /root/miniconda3/envs/lynn/lib/python3.8/site-packages/torch_npu/dynamo/torchair/__init__.py:3: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

../../../root/miniconda3/envs/lynn/lib/python3.8/site-packages/pkg_resources/__init__.py:2871
  /root/miniconda3/envs/lynn/lib/python3.8/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

tests/test_big_modeling.py::BigModelingTester::test_cpu_offload_gpt2
tests/test_big_modeling.py::BigModelingTester::test_disk_offload_gpt2
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_gpt2_on_two_devices
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_gpt2_on_two_devices
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_gpt2_on_two_devices
  /root/miniconda3/envs/lynn/lib/python3.8/site-packages/urllib3/connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host '90.253.25.58'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
    warnings.warn(

tests/test_big_modeling.py::BigModelingTester::test_cpu_offload_gpt2
tests/test_big_modeling.py::BigModelingTester::test_disk_offload_gpt2
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_gpt2_on_two_devices
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_gpt2_on_two_devices
tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_gpt2_on_two_devices
  /root/miniconda3/envs/lynn/lib/python3.8/site-packages/transformers/generation/utils.py:1132: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
    warnings.warn(

tests/test_big_modeling.py::BigModelingTester::test_cpu_offload_gpt2
tests/test_big_modeling.py::BigModelingTester::test_disk_offload_gpt2
  /root/miniconda3/envs/lynn/lib/python3.8/site-packages/transformers/generation/utils.py:1460: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on npu, whereas the model is on meta. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('meta') before running `.generate()`.
    warnings.warn(

tests/test_big_modeling.py::BigModelingTester::test_dispatch_model_copy
  /root/miniconda3/envs/lynn/lib/python3.8/site-packages/torch_npu/utils/storage.py:38: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
    if self.device.type != 'cpu':

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================== 24 passed, 8 skipped, 15 warnings in 82.22s (0:01:22) ==============================================================================

```

**Comment by muellerzr** [comment]
@statelesshz just ping me when we're ready for a final review :)

**Comment by statelesshz** [comment]
@muellerzr this PR is ready for review :)
Due to the lack of support for `torch.Tensor.to()`, some test cases fail on the MPS device :(.

image

**Review by muellerzr — APPROVED** [review]
Thanks for doing this!

**Pull request merged**
