### PR TITLE
FIX: add oneCCL environment variable for non-MPI launcher (accelerate launch)

### PR DESCRIPTION
**Pull request by faaany**
## What does this PR do?

- Fixes issue https://github.com/huggingface/accelerate/issues/2340 fort both deepspeed path and none-deepspeed path 
- Adds the missing `LOCAL_WORLD_SIZE` environment variable

### CODE REVIEW

**Comment by faaany** [comment]
+ @sgugger

**Comment by muellerzr** [comment]
@faaany can you do pip install -e .[quality] and do make style; make quality please?

**Comment by faaany** [comment]
> @faaany can you do pip install -e .[quality] and do make style; make quality please?

done. Could you pls review it? thanks!

**Review by muellerzr — APPROVED** [review]
Thanks!

**Pull request merged**
