### PR TITLE
Make test assertions more idiomatic

### PR DESCRIPTION
**Pull request by akx**
# What does this PR do?

This PR makes the assertions used in the test suite [more idiomatic for Pytest](https://docs.pytest.org/en/stable/how-to/assert.html).

Idiomatic assertions are rewritten by Pytest, making debugging much easier.

Namely, I did a first pass using [codemod-unittest-to-pytest-asserts](https://github.com/akx/codemod-unittest-to-pytest-asserts), followed by some `ast-grep` powered fixes, followed up with some manual fixes to make things neater still.

Sibling of https://github.com/huggingface/trl/pull/1301.

I don't have easy access to hardware suitable for running all tests locally (Apple Silicon 😄), but the tests I could run seem to pass, so here's hoping CI agrees!

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

cc @muellerzr

### CODE REVIEW

**Review by muellerzr — CHANGES_REQUESTED** [review]
No, it is standard with Hugging Face that we use unittest for our testing suite centralization, not pytest (the pytest part is just for when we need to, such as scripts that need to be ran on multiple devices). to avoid things like this (and the other PRs you have opened that are very, very large changes) can we please open an issue first to discuss them before much time is spent on them? Thanks!

**Review by muellerzr — CHANGES_REQUESTED** [review]
We've decided not to go ahead with this, as our mixture of some pytest and mostly unittest + our own features is a better long-term approach we've found that maintains usability and longevity without the nuances and issues that pytest can provide long-term. Thank you though for your thoughts on the matter!

**Comment by muellerzr** [comment]
We may change our mind in the future (and you're welcome to keep this PR open as a result) but for now that's where we're at here :)

**Comment by akx** [comment]
> as our mixture of some pytest and mostly unittest + our own features

TBH, the current tests are already mixing e.g. `self.assertRaises` and `pytest.raises` within the same file, so there's no way to run the tests without `pytest` anyway. (See e.g. `test_state_checkpointing.py`) 😅  

> is a better long-term approach we've found that maintains usability and longevity without the nuances and issues that pytest can provide long-term. 

What nuances and issues have you found that Pytest provides long-term?

Anyway, I rebased this and backed out the last commit that made things more Pytesty, so now all this does is codemod `unittest`-specific assertions into native Pythonic assertions.

**Comment by muellerzr** [comment]
> TBH, the current tests are already mixing e.g. self.assertRaises and pytest.raises within the same file, so there's no way to run the tests without pytest anyway. (See e.g. test_state_checkpointing.py) 😅

yes, hence why pytest is a dep in the testing requirements install.

**Review by muellerzr — APPROVED** [review]
Sorry for the pushback on this, we had a lengthy discussion internally yet again at the start of the week and are okay with using *some* things more py-testy rather than using unittest explictly such as this. 

Thanks for your contribution!

**Comment by akx** [comment]
@muellerzr 

> Edit: can you run `make style; make quality` however?

Rebased + done.

**Comment by fxmarty** [comment]
I don't understand the point. Pytest works smoothly with unittest, why change something that is already working?

**Comment by BenjaminBossan** [comment]
@fxmarty We had some internal discussion to allow using more pytest features going forward. For some of these features, we need to get rid of `unittest.TestCase`, which requires removing `self.assertFoo` type calls. Going from `self.assertFoo` to `assert` is also more readable and we're still getting nice error messages.

**Comment by fxmarty** [comment]
@BenjaminBossan Thank you, which features would that be?

**Pull request merged**
