### PR TITLE
devcontainer: "extensions" has been removed and replaced by customizations

### PR DESCRIPTION
**Pull request by dbpprt**
"extensions" has been moved to "customizations/vscode"

```
"customizations": {
        "vscode": {
            "extensions": [
                // Ensure we have IntelliSense in VSCode when running inside container
                "ms-python.python"
            ]
        }
    }
```

### CODE REVIEW

**Comment by sgugger** [comment]
Let's cc @Chris-hughes10 who authored this.

**Comment by Chris-hughes10** [comment]
This is a response to a breaking change in the remote container extension and is the change that I would make. @dennisbappert have you verified that the dev container builds correctly with the new version?

**Comment by dennisbappert** [comment]
I tested the "default" configuration, so CPU image. 

image


I only tested it and do not use this configuration for development, I'm using my own dev container boilerplate.

**Comment by dennisbappert** [comment]
Let me investigate further.

**Comment by dennisbappert** [comment]
#1087

**Comment by sgugger** [comment]
That's fine by me if it also works for @dbpprt

**Pull request merged**
