### PR TITLE
remove check for main process for trackers initialization

### PR DESCRIPTION
**Pull request by Gladiator07**
Made the changes as discussed in [this PR](https://github.com/huggingface/accelerate/pull/642#issuecomment-1220651885).

@muellerzr

### CODE REVIEW

**Comment by muellerzr** [comment]
Thanks! Do you want to try to update the complete examples in this too? (The last spot would be in the docs, but I can update that :) )

**Comment by Gladiator07** [comment]
Sure, I will update all the example scripts in the `examples` folder in this PR :)

**Comment by muellerzr** [comment]
@Gladiator07 great! It should just be the complete_nlp_example and complete_cv_example

**Comment by Gladiator07** [comment]
@muellerzr but many of the example scripts have the `is_main_process` check (for instance [here](https://github.com/huggingface/accelerate/blob/a3d94916a87d07471865261d015128870f513c38/examples/by_feature/deepspeed_with_config_support.py#L594)). Should I update them as well or just `complete_nlp_example` and `complete_cv_example` ?

**Comment by muellerzr** [comment]
Ah, great point! Yes in that case those would be great to have done as well! :)

**Comment by Gladiator07** [comment]
Hi @muellerzr, I have removed the `is_main_process` check from all example scripts. Please check it once.

**Review by muellerzr — APPROVED** [review]
Great work!

**Pull request merged**
