### PR TITLE
Move `new_forward` function to global to make pickle happy

### PR DESCRIPTION
**Pull request by feisuzhu**
# What does this PR do?

We need to pickle bnb quantized modules for some reason, and the hooking mechanism make it impossible due to the `new_forward` function inside `add_hook_to_module` being a closure. Moving it to global, and nothing else.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

@sgugger @muellerzr

### CODE REVIEW

**Comment by muellerzr** [comment]
Hi! Thanks for the PR, Sylvain hasn't worked at Hugging Face for over half a year by now, please follow the guide when opening a PR on who to @ mention.

cc @SunMarc

**Comment by SunMarc** [comment]
Any news @feisuzhu ?

**Comment by feisuzhu** [comment]
Ah, sorry about the silence. I have found a workaround to our specific problem so this PR is irrelevant to me now. If this PR seems weird anyways please just close it.

Background:
I'm pickling the result of `XXXX.from_pretrained(..., load_in_8bit=True)` and the added hooks prevent this from happening. But later I found that the hooks are not mandatory (I'm managing where to put tensors manually) so I just removed them.

**Comment by SunMarc** [comment]
Sounds good ! Note that you can remove the hooks using `remove_hook_from_module`.

**Comment by arpit2665** [comment]
> Ah, sorry about the silence. I have found a workaround to our specific problem so this PR is irrelevant to me now. If this PR seems weird anyways please just close it.
> 
> Background: I'm pickling the result of `XXXX.from_pretrained(..., load_in_8bit=True)` and the added hooks prevent this from happening. But later I found that the hooks are not mandatory (I'm managing where to put tensors manually) so I just removed them.

Hi @feisuzhu - We are also trying to pickle the model and facing an issue with the same. Could you please explain how did you resolve it?

#2749

**Comment by arpit2665** [comment]
Hi @feisuzhu   Can you please explain how did you manage to pickle the quantized model?

**Comment by feisuzhu** [comment]
@arpit2665 

1. Remove hooks and monkey patched methods

```python
    def _remove_accelerate_hooks(self, model):
        import torch

        if not isinstance(model, torch.nn.Module):
            return model

        # Remove AlignDevices hooks
        from accelerate.hooks import remove_hook_from_module
        remove_hook_from_module(model, True)

        # Remove accelerate added warning hooks (interferes pickling)
        model.__dict__.pop('to', None)
        model.__dict__.pop('cuda', None)
        model.__dict__.pop('xpu', None)
        model.__dict__.pop('npu', None)

        return model
```

2. Handle `bitsandbytes` params manually

```python

def _reduce_bnb_param(p):
    assert p.quant_state
    qs_dict = p.quant_state.as_dict(packed=True)
    return (_rebuild_bnb_param, (type(p), p.data, qs_dict))


def _rebuild_bnb_param(typ, data, qs_dict):
    return typ.from_prequantized(data, qs_dict, device='cpu')


ForkingPickler.register(bitsandbytes.nn.modules.Params4bit, _reduce_bnb_param)
ForkingPickler.register(bitsandbytes.nn.modules.Int8Params, _reduce_bnb_param)
```

You must manually manage which device to put your tensors during pickling/unpickling process.

**Pull request closed without merging**
