### PR TITLE
ccl version check and import different module according to version

### PR DESCRIPTION
**Pull request by sywangyi**
Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

### CODE REVIEW

**Comment by sywangyi** [comment]
@liangan1 @yao-matrix @sgugger please have a review

**Comment by muellerzr** [comment]
Thanks for this! Looks great to me 😄 could you run `make style; make quality` to get past that failure please? And then we're good!

**Comment by sywangyi** [comment]
@muellerzr thanks for the suggestion, fix the "make quality" issue.

**Review by sgugger — APPROVED** [review]
Thanks for your PR!
Looks like this conflicts with an earlier PR #554 but yours is more complete. Could you just solve the merge conflict so we can merge?

**Pull request merged**
