### PR TITLE
Don't unwrap in save_state()

### PR DESCRIPTION
**Pull request by cccntu**
I think this is a simple fix for #285 

I haven't test this. Just looking for feedback first.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks a lot for your PR!

I think this is sensible since the `save_state` definitely happens after `prepare`, as does `load_state` but double-checking with @muellerzr

**Comment by muellerzr** [comment]
Since this went unnoticed, might be good to add in a deepspeed test to the checkpointing test available here: https://github.com/huggingface/accelerate/blob/main/tests/test_state_checkpointing.py

If you think you can manage that feel free to add it to this PR, worst case I can add it in as a follow up

**Comment by cccntu** [comment]
Hi, although this solves the model weights issue, but now it fails when loading optimizer states.

Because deepspeed `optimizer.state_dict()` returns a dictionary.
https://github.com/microsoft/DeepSpeed/blob/9305916d6b858b20fca3ebe03940ceaaa13cdfbd/deepspeed/runtime/zero/stage_1_and_2.py#L1998

But deepspeed `optimizer.load_state_dict()`  expects a list of dictionary.
https://github.com/microsoft/DeepSpeed/blob/9305916d6b858b20fca3ebe03940ceaaa13cdfbd/deepspeed/runtime/zero/stage_1_and_2.py#L2135-L2167
because deepspeed `load_checkpoint` actually gets multiple state_dict (one for each partition or something) https://github.com/microsoft/DeepSpeed/blob/9305916d6b858b20fca3ebe03940ceaaa13cdfbd/deepspeed/runtime/engine.py#L2650

So I think I will just use this
```
if accelerator.distributed_type == DistributedType.DEEPSPEED:
    model.load_checkpoint(path)
    model.save_checkpoint(path)
else:
    accelerator.load_state(path)
    accelerator.save_state(path)
```

**Comment by cccntu** [comment]
Since the test I tried to add fails when loading optimizer, I won't push it here. Please feel free to merge or close this PR.

**Comment by sgugger** [comment]
Let's merge this first fix (thanks a lot!). Cc @pacman100 for the second test.

**Pull request merged**
