### PR TITLE
Avoid double wrapping of all accelerate.prepare objects

### PR DESCRIPTION
**Pull request by muellerzr**
Solves double nested wrapping issues linked as a side-effect to https://github.com/huggingface/transformers/issues/24050.

Also resets step to 0 during free_memory

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks!

**Comment by Yura52** [comment]
@muellerzr @sgugger Hi! I have zero familiarity with the code base, but is it intentional that the added `setattr()` call sets the "_is_accelerate_prepared" attribute, while the used `getattr()` calls access the different "_accelerate_prepared" (note missing "_is" suffix) attribute?

**Comment by muellerzr** [comment]
Nope, it is not! Would you like to put in a fix @Yura52? Otherwise I can do so quickly :)

**Comment by Yura52** [comment]
> Nope, it is not! Would you like to put in a fix @Yura52? Otherwise I can do so quickly :)

Here is the PR: #1560

**Pull request merged**
