### PR TITLE
fix: add debug argument to sagemaker configuration

### LINKED ISSUE #1903: SageMaker config TypeError
### System Info

```Shell
- `Accelerate` version: 0.22.0
- Platform: Linux-5.10.184-175.731.amzn2.x86_64-x86_64-with-glibc2.26
- Python version: 3.10.8
- Numpy version: 1.25.2
- PyTorch version (GPU?): 2.0.1+cu117 (False)
- PyTorch XPU available: False
- PyTorch NPU available: False
```


### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Install accelerate[sagemaker]
2. run `accelerate config`
3. Go through the configuration process

The result will be:
```
Traceback (most recent call last):                                                                                                                                                                                                                                            
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/bin/accelerate", line 8, in <module>                                                                                                                                                                                   
    sys.exit(main())                                                                                                                                                                                                                                                          
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main                                                                                                                                  
    args.func(args)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/accelerate/commands/config/config.py", line 67, in config_command
    config = get_user_input()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/accelerate/commands/config/config.py", line 38, in get_user_input
    config = get_sagemaker_input()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/accelerate/commands/config/sagemaker.py", line 243, in get_sagemaker_input
    return SageMakerConfig(
TypeError: SageMakerConfig.__init__() missing 1 required positional argument: 'debug'
```

### Expected behavior

accelerate config works

### PR DESCRIPTION
**Pull request by maximegmd**
Fixes #1903

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Thanks! Can you run `make style; make quality` and we can go ahead and merge?

**Comment by BenjaminBossan** [comment]
Just a question, should `debug` be hard-coded to `False` or should it be configurable similar to [here](https://github.com/huggingface/accelerate/commit/b3fc3c9067880a4bd4ea49bedc1e8c3d810b84ab#diff-6c20200336bcfbfe6add9733ea5df6e878e4612903d32f733c370d6d247af1de)? Maybe it wouldn't work or make sense for sagemaker, not sure.

**Review by muellerzr — APPROVED** [review]
Thanks, solution makes sense to me there!

**Review by BenjaminBossan — APPROVED** [review]
Thanks for adjusting and thanks for explaining. LGTM.

**Pull request merged**
