### PR TITLE
Remove out-dated xpu device check code in `get_balanced_memory`

### PR DESCRIPTION
**Pull request by faaany**
## What does this PR do?
This PR removes the outdated and unnecessary code of xpu device check in the following code snippet
```python
if (
                    d != "cpu"
                    and (torch.device(d).type == "xpu" or torch.xpu.get_device_properties(d).dev_type == "gpu")
                )
```
The reasons are 
- If torch.xpu.get_device_properties(d) works, torch.device(d).type will always be "xpu"
- If torch.device(d).type == "xpu", `d` will definitively not be "cpu"

`torch.device(d).type == "xpu"` is enough to check xpu device just like the case in MLU and  NPU.

## Who can review?
@SunMarc and @muellerzr

### CODE REVIEW

**Comment by faaany** [comment]
@abhilash1910

**Review by muellerzr — COMMENTED** [review]
Thanks! Love the simplification 😍 

Could we actually take this a bit further now that the logic is aligned?

Perhaps getting the device type expected under the `is_xxx_available()` and then only calling the 
```python
num_devices = len([d for d in max_memory if torch.device(d).type == expected_device_type and max_memory[d] > 0])
```

section once? WDYT

**Comment by abhilash1910** [comment]
Yes @muellerzr  looks like a good abstraction, We are internally validating the "gpu" predicate of the validation logic . 
If it is no longer required then new design LGTM.

**Review by SunMarc — APPROVED** [review]
LGTM !

**Comment by faaany** [comment]
@muellerzr PR updated with `expected_device_type`, pls review, thx!

**Review by abhilash1910 — APPROVED** [review]
LGTM

**Review by muellerzr — APPROVED** [review]
Beautiful 😍 

Nice work!

**Pull request merged**
