### PR TITLE
Optimize the megatron plugin

### PR DESCRIPTION
**Pull request by zhangsheng377**
Optimize the megatron plugin, and make the megatron's version to r0.5.0.
https://github.com/huggingface/accelerate/pull/2501#issuecomment-2126931526
https://github.com/huggingface/accelerate/issues/2390#issuecomment-2136834517

### CODE REVIEW

**Comment by zhangsheng377** [comment]
@muellerzr  @pacman100

**Comment by muellerzr** [comment]
Hey @zhangsheng377, let me give it a look now. FYI Sourab is no longer a part of HF, so I will be taking up Megatron/DS/FSDP

**Comment by zhangsheng377** [comment]
> Hey @zhangsheng377, let me give it a look now. FYI Sourab is no longer a part of HF, so I will be taking up Megatron/DS/FSDP

It's really unfortunate to hear about Sourab's departure. I will try to modify the code format shortly. Thank you for letting me know.

**Review by muellerzr — APPROVED** [review]
Thanks we can go ahead and merge this. Why do you want permissions to be a committer out of curiosity?

**Comment by zhangsheng377** [comment]
> Thanks we can go ahead and merge this. Why do you want permissions to be a committer out of curiosity?

Thank you. Because I have a strong interest in open source, I think the Accelerate project is very promising. 
And my current working is training large models with Megatron, so I think I can contribute to Accelerate. (By the way, I also contributed distributed LoRa features to PEFT 😃)

**Comment by muellerzr** [comment]
For security reasons, you can only be at most a contributor, and we need to manually approve running the CI. However you have contributed to this project and it will show up in github as such :)

**Pull request merged**
