### PR TITLE
changes required for DS integration

### PR DESCRIPTION
**Pull request by pacman100**
### What does this PR do?
1. Changes to be made for integrating accelerate in Transformers

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Works for me, thanks!

**Review by muellerzr — APPROVED** [review]
Thanks!

**Comment by jeffra** [comment]
@pacman100, we're seeing DS integration tests failing after this commit :(

https://github.com/microsoft/DeepSpeed/actions/runs/4941257007/jobs/8833704256?pr=3505

**Comment by pacman100** [comment]
Hello @jeffra, Thank you for the quick notification. PR #1411 should resolve this.

**Pull request merged**
