### PR TITLE
Fix type hints for PEP 484 compliance, enable UP007

### PR DESCRIPTION
**Pull request by akx**
# What does this PR do?

This PR runs [`no_implicit_optional`](https://github.com/hauntsaninja/no_implicit_optional) to make the type hinting compliant with [PEP 484](https://peps.python.org/pep-0484/) (see the readme for `no_implicit_optional` for context), IOW more accurate.

It then enables the previously-disabled `UP007` Ruff rule to make the type annotations shorter (`X | Y`) where possible. (Since not all modules are using `from __typing__ import annotations`, and `accelerate` targets Python 3.8+, that's not everywhere. Targeting Python 3.10 will enable `X | Y` everywhere, see [PEP 604](https://peps.python.org/pep-0604/).)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

cc @muellerzr @BenjaminBossan

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
We have a mix of `Optional[Foo]` and `Foo | None`, I wonder if we should favor one way over the other, at least for newly added code.

**Comment by akx** [comment]
> We have a mix of `Optional[Foo]` and `Foo | None`, I wonder if we should favor one way over the other, at least for newly added code.

Unless you know there's code that needs introspection of annotation objects, I would recommend every file to have `from __typing__ import annotations` (which can be automated with Ruff).

**Comment by BenjaminBossan** [comment]
> Unless you know there's code that needs introspection of annotations, I would recommend every file to have `from __typing__ import annotations` (which can be automated with Ruff).

I've been adding this import to PEFT and haven't encountered any issues. We use types very loosely anyway, I think that should be fine. I assume that the implication is that if we add `from __future__ import annotations` everywhere, we can use the `|` pattern instead of `Optional`?

**Comment by akx** [comment]
> I assume that the implication is that if we add `from __future__ import annotations` everywhere, we can use the `|` pattern instead of `Optional`?

Yes. Enabling the future makes all annotations not actually evaluated at runtime, IOW they can use syntax that the concrete types won't support in the target interpreter version. (What a convoluted sentence!)

In other words, even if for Python 3.8 the concrete Type type doesn't support the `|` operator to turn it to an `Union` of itself and another type, type checkers such as Mypy and Pyright are smart enough to support the syntax as they're just reading the AST.

The flipside is that libraries that do require evaluating annotations (such as Pydantic) will require additional smarts to evaluate the deferred annotations, but the mainstream libraries (such as Pydantic) already support this in recent versions.

**Comment by muellerzr** [comment]
For newly added code I agree we can just stick with `|`, the import will help fix anyone on a lower python version that doesn't support it "natively" yet. And at least getting started with this is good enough, as in general while we don't strictly type everything this is enough of a starting point

**Comment by muellerzr** [comment]
@akx do you want to go ahead and include `from __typing__ import annotations` + the ruff rule for it? :)

**Comment by akx** [comment]
@muellerzr I can do that in a follow-up PR to keep things clean and easier to review?

**Comment by muellerzr** [comment]
Although, since we have the type annotations here being used, let's just add it here as our CI runs python 3.8 iirc so it'll just immediately break

**Comment by akx** [comment]
@muellerzr Are you sure you want it here? The diff looks to be `121 files changed, 374 insertions(+), 234 deletions(-)`...

**Comment by muellerzr** [comment]
Perhaps not...!

**Review by BenjaminBossan — APPROVED** [review]
Apart from the merge conflict, LGTM.

**Comment by BenjaminBossan** [comment]
I just saw that we have other incorrectly typed optionals, outside of function signatures, e.g. here:

https://github.com/huggingface/accelerate/blob/21b225e8d556cf979ac60ba017af9a5cdfd6c8db/src/accelerate/commands/config/config_args.py#L183-L201

Those don't seem to be caught by `no_implicit_optional`. Not a blocker for this PR, just something to keep in mind.

**Comment by BenjaminBossan** [comment]
> Unless you know there's code that needs introspection of annotations

There does indeed appear to be a problem with `HfArgumentParser`: https://github.com/huggingface/peft/pull/1537

**Comment by akx** [comment]
> There does indeed appear to be a problem with `HfArgumentParser`: [huggingface/peft#1537](https://github.com/huggingface/peft/pull/1537)

... but only for `dataclasses`, which this PR doesn't touch 😄

**Comment by muellerzr** [comment]
But for downstream libraries that rely on accelerate and will want to integrate with the HfArgumentParser, this could matter.

**Comment by akx** [comment]
@muellerzr As I see it, HfArgumentParser only tries to parse annotations for class fields, not function arguments.

And anyway, ` | ` style annotations have been in `main` since at least April 2023, see e.g. https://github.com/huggingface/accelerate/blob/main/src/accelerate/accelerator.py#L249-L266

**Comment by BenjaminBossan** [comment]
Let's revive this PR.

**Pull request closed without merging**
