### PR TITLE
Add examples to tests

### PR DESCRIPTION
**Pull request by muellerzr**
# What does this PR do?

Adds trainer integration tests (the examples) to our test suite since they test both the `Trainer` and the `Accelerator`

### CODE REVIEW

**Comment by pacman100** [comment]
A general query I had. Would this mean the same tests are being run by both Transformers CI as well as Accelerate CI? That would be redundant compute spent which seems suboptimal.

**Review by pacman100 — COMMENTED** [review]
A general query I had. Would this mean the same tests are being run by both Transformers CI as well as Accelerate CI? That would be redundant compute spent which seems suboptimal.

**Comment by muellerzr** [comment]
Yes, but they are in our main CI logs so we can pick them up early,we don’t have to rely on transformers. It’s why we have the integration test CI

**Review by BenjaminBossan — APPROVED** [review]
Thanks. I agree that as long as those are not hugely expensive tests, it's a worthwhile addition to gain visibility.

**Comment by muellerzr** [comment]
They add ~10 min to the PR CI, hence why they are just in merge and nightlies (as it should take less time than that).

**Pull request merged**
