### PR TITLE
fix potential OOM when resuming with multi-GPU training

### PR DESCRIPTION
**Pull request by exhyy**
When resuming from a checkpoint, only the model will be loaded to different GPUs, which might cause OOM.

Background: 
I encounter an OOM error when attempting to resume training ControlNet from a checkpoint using 4 GPUs 12GB each. After making modifications to the code, this error (OOM) has been fixed.

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
This only applies to the optimizer state. Scheduler, grad scaler or RNG states do not need this.

Also cc @muellerzr

**Comment by exhyy** [comment]
Thanks for replay! Code updated and it works fine for me!

**Review by sgugger — APPROVED** [review]
Thanks! Waiting for a second look from @muellerzr and then should be good to merge.

**Review by muellerzr — APPROVED** [review]
Makes sense to me! I did wonder at some point if the optimizer state needed to be mapped as well, nice catch :)

**Pull request merged**
