### PR TITLE
enhance compatibility of honor type

### LINKED ISSUE #237: typing (list/tuple/dict) in accelerate.utils
Hi, 

I can't help noticing the typing in accelerate.utils is a bit messy.

The type check for `dict` is actually `Mapping` (which I think is a better approach as it allows user defined `Mapping`, maybe there needs some doc work.
And the type check for list/tuple is `(list, tuple)` which I believe `Sequence` could works better. 

Also, https://github.com/huggingface/accelerate/blob/main/src/accelerate/utils.py#L119-L122 has specific behavior for type `namedtuple` and may not work with some other type, maybe it's better to use EAFP here?

```python
    try:
        return type(obj)(generator)
    except TypeError:
        return type(obj)(*list(generator))
```

### PR DESCRIPTION
**Pull request by ZhiyuanChen**
fixes #237

### CODE REVIEW

**Review by ZhiyuanChen — COMMENTED** [review]
Maybe it would be better if we raise an exception here if cannot re-instantiation the original type

**Review by sgugger — APPROVED** [review]
What did you have in mind? The second try will raise an exception if it doesn't succeed so we will already have something.

Thanks a lot for your PR in any case!

**Comment by ZhiyuanChen** [comment]
Sorry I was on my Chinese new year leave and just get back.
Yeah I do agree this should raise exact error with enough information for debugging.

**Comment by sgugger** [comment]
Could you just run `male style` on your branch so we can merge this?

**Comment by ZhiyuanChen** [comment]
hi, I just noticed the existence of this pr......
I've fixed the linting issue related to this pr, but there seems to be more on other code

**Comment by sgugger** [comment]
Seems like the checks are all passing now, thanks again!

**Pull request merged**
