### PR TITLE
🚨🚨🚨Move to using tags rather than latest for docker images and consolidate image repos 🚨 🚨🚨

### PR DESCRIPTION
**Pull request by muellerzr**
# What does this PR do?

Rather than having `huggingface/accelerate-gpu` `huggingface/accelerate-cpu` + a new repository for *each new env that we will add* (e.g. soon to be XLA and XLA_gpu), this PR centralizes all our docker images to just be in `huggingface/accelerate` and uses the right tags to make discovery and management easier.

This PR also includes a README in `/docker` which mentions what images are available and how to run things.

The Pros:

* Easier discoverability of images based on tags, rather than needing to know the full repo
* Easier interoperability and debugging as images now have nightly tags associated with the date they were ran
* Allows for easier fine-grained tagging and build management to use later on (such as `deepspeed` specific builds, XLA-specific builds, etc, which now can be pushed as a seperate tag instead of needing to make a ton of new repos)

The Cons:

* Downstream users using `huggingface/accelerate-cpu` or `huggingface/accelerate-gpu` will not receive updated images.

Not sure if there's a good way to alert users to the deprecation inside Docker, so we'll just need to do so thoroughly in comms.

## The conversion:

* `huggingface/accelerate-gpu:latest` -> `huggingface/accelerate:gpu-nightly`
* `huggingface/accelerate-cpu:latest` -> `huggingface/accelerate:cpu-nightly`
## New image tags

Nightlies are now built with versioning in mind for individuals to roll back to easily (or CI's). This helps us easily trakc down if a new dependency got released, when it happened, and what was new in the build.

* `huggingface/accelerate:{gpu,cpu}-nightly`
* `huggingface/accelerate:{gpu,cpu}-nightly-{YYYY}-{MM}-{DD}`

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ydshieh @BenjaminBossan

### CODE REVIEW

**Comment by muellerzr** [comment]
New repo is located here: https://hub.docker.com/r/huggingface/accelerate/tags

Looking at migrating the `README.md` to the repo currently

**Review by ydshieh — APPROVED** [review]
LGTM, thanks.

> Huggingface/accelerate-gpu:latest -> huggingface/accelerate:gpu-latest
I think we don't have tag containing `-latest` anymore.

Regarding how long to keep the images, I still think it's better to talk (or at least inform) the infra team. Not sure how large is an `accelerate` image, but `transformers` images are of around ~10G. (And I don't know if we will get problems when we have hundred of such images 😆 )

**Comment by muellerzr** [comment]
> I think we don't have tag containing -latest anymore.

Thanks, yup adjusted as it's `-nightly` now

> Regarding how long to keep the images, I still think it's better to talk (or at least inform) the infra team. Not sure how large is an accelerate image, but transformers images are of around ~10G. (And I don't know if we will get problems when we have hundred of such images 😆 )

Definitely the next step. Accelerate images on `Docker` are also around 10gb

**Review by BenjaminBossan — APPROVED** [review]
The reason for these changes make sense to me. As mentioned, the question about retention should probably be addressed.

Regarding the deprecation, there doesn't seem to be an official way: https://github.com/docker/hub-feedback/issues/907. Not sure what can be done, really, except for mentioning it in the release notes.

**Comment by muellerzr** [comment]
> Not sure what can be done, really, except for mentioning it in the release notes.

@BenjaminBossan I more or less plan on doing the following:

1. The official README in the repos will be updated to include a big deprecation notification and what to migrate to
2. We'll publish one more release of the images, stating a PRINT statement on entry to the container that the image is deprecated and to migrate (NVIDIA does this, it stands to reason we can too)


Next steps from here are more fine-grained builds as needed internally and externally
* A `DeepSpeed` specific build (tag: `accelerate:cuda-deepspeed`)
* A `TransformerEngine` + `MS-AMP` specific build (tag: `accelerate-cuda-fp8`)

**Pull request merged**
