### PR TITLE
Use total_batch_size when using `DataLoaderShard`

### PR DESCRIPTION
**Pull request by ZhiyuanChen**
# What does this PR do?

dataloader will be wrapped by `DataLoaderShard` after preparation. After preparation, the `batch_size` attribute is no longer available and will be set to None. This would arise issue in deepspeed training. 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@muellerzr 

Although this is not a bug with deepspeed... @pacman100

### CODE REVIEW

**Review by muellerzr — COMMENTED** [review]
Thanks for the PR! Any chance you could do `make style; make quality`? Thanks!

**Comment by ZhiyuanChen** [comment]
Sorry, will do that next week.

**Comment by pacman100** [comment]
Hello @ZhiyuanChen, could you please elaborate `This would arise issue in deepspeed training.` with a minimal example of reproducing the said issue, Thank you!

**Comment by ZhiyuanChen** [comment]
> Hello @ZhiyuanChen, could you please elaborate `This would arise issue in deepspeed training.` with a minimal example of reproducing the said issue, Thank you!

```
accelerator = Accelerator()
dataloader = Dataloader(dataset)
accelerator.prepare(dataloader)
accelerator.prepare(dataloader)
```

ValueError: At least one of the dataloaders passed to `accelerate.prepare()` has `None` as batch size. Please set an integer value in `train_micro_batch_size_per_gpu` in the deepspeed config file or assign integer value to `AcceleratorState().deepspeed_plugin.deepspeed_config['train_micro_batch_size_per_gpu']`.

**Comment by muellerzr** [comment]
@ZhiyuanChen why are we double preparing the dataloader here? That shouldn't happen/is part of the API

**Comment by ZhiyuanChen** [comment]
> @ZhiyuanChen why are we double preparing the dataloader here? That shouldn't happen/is part of the API

The accelerator for other backend does not have this issue. They explicitly check if any of `*args` is prepared and ignore the prepared element. 

This PR ensure the consistency across the API. 

In my case, my runner have a `__post_inti__` method like `dataclass`, which is used to prepare everything. Sometimes, if the user have already prepared dataloader, it will prepare it again.

**Comment by muellerzr** [comment]
In that case let's add a test for your use case then please

**Review by pacman100 — COMMENTED** [review]
Thank you @ZhiyuanChen for providing the necessary context. The PR does address the issue and looks good to me. As Zach mentioned, a simple test in `tests/deepspeed/test_deepspeed.py` would be great, after that good to merge.

**Comment by ZhiyuanChen** [comment]
> Thank you @ZhiyuanChen for providing the necessary context. The PR does address the issue and looks good to me. As Zach mentioned, a simple test in `tests/deepspeed/test_deepspeed.py` would be great, after that good to merge.

Thank you~ 
Sorry I'm applying to PhD program these weeks and am extremely busy. I may be slow on adding the tsets

**Pull request closed without merging**
