### PR TITLE
checks if MLU is available via cndev

### PR DESCRIPTION
**Pull request by huismiling**
# What does this PR do?

Checks if mlu is available via an cndev-based check which won't trigger the drivers and leave mlu uninitialized.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by huismiling** [comment]
Hi @muellerzr , could you help to review this PR ?

**Review by BenjaminBossan — COMMENTED** [review]
I think this could be simplified by using the [`patch_environment`](https://github.com/huggingface/accelerate/blob/939ce400cbc0478fd281b9fcc9a2a85691ba9f7d/src/accelerate/utils/other.py#L246) function.

**Review by muellerzr — COMMENTED** [review]
Agree with @BenjaminBossan here, otherwise that's a good solution to me!

**Comment by huismiling** [comment]
@BenjaminBossan `patch_environment` is very good . 
But there is Error when `from .other import patch_environment` is used in accelerate/utils/imports.py.
`ImportError: cannot import name 'ComputeEnvironment' from partially initialized module 'accelerate.utils' (most likely due to a circular import)`

**Comment by BenjaminBossan** [comment]
Damn circular imports. You would have to import `patch_environment` locally (with a comment that it's to avoid circular imports) or move the function to a different module. Probably the former is more practical, WDYT @muellerzr.

**Comment by muellerzr** [comment]
Agreed, if we must, former would be the way to go

**Comment by huismiling** [comment]
What is the `former` ? I have no idea what I should do.

**Comment by muellerzr** [comment]
Importing the func inside the function using it, with a comment explaining that it's there to avoid circular imports

**Comment by huismiling** [comment]
> Importing the func inside the function using it, with a comment explaining that it's there to avoid circular imports

like this ?  This cause `circular import`, too. 

```
def is_mlu_available(check_device=False):
    if importlib.util.find_spec("torch_mlu") is None:
        return False

    import torch_mlu  # noqa: F401
    from .other import patch_environment

    with patch_environment(PYTORCH_CNDEV_BASED_MLU_CHECK="1"):
        available = torch.mlu.is_available()

    return available
```

**Comment by BenjaminBossan** [comment]
> This cause `circular import`, too.

Ouch, this is because `is_mlu_available()` is called on root level here:

https://github.com/huggingface/accelerate/blob/3fcc9461c4fcb7228df5e5246809ba09cfbb232e/src/accelerate/state.py#L57-L58

So IMO the right way would be to move `patch_environment` to a separate module. Reimporting it to `other.py` should still work, so for users nothing would change. WDYT @muellerzr?

**Pull request closed without merging**
