### PR TITLE
fix backend check

### PR DESCRIPTION
**Pull request by jiqing-feng**
Hi @muellerzr . This PR fixed the backend assignment. It avoids confusing backend checks and distributed_type checks. We should assign distributed_type by env first and then decide whether to assign backend.

Do you know how to add a proper test to avoid this issue? Please let me know, and I will add it : )

### CODE REVIEW

**Review by muellerzr — COMMENTED** [review]
Sure, I'm open to this, so long as the tests pass. The tests specifically are all of the tests, which are run on XPU and multi-CPU hardware. 

A simple check is `accelerate test` if you have the hardware available. If not let me know

**Comment by jiqing-feng** [comment]
> Sure, I'm open to this, so long as the tests pass. The tests specifically are all of the tests, which are run on XPU and multi-CPU hardware.
> 
> A simple check is `accelerate test` if you have the hardware available. If not, let me know

Hi @muellerzr, The `accelerate test` runs well. We can merge this PR to fix the problem as soon as possible, but we'd better design a test in CI to check that the configs are correctly assigned considering the long term.

**Comment by zhangsheng377** [comment]
@muellerzr 
This modification changes all MULTI_GPU and MULTI_NPU to MULTI_CPU, right?

**Comment by muellerzr** [comment]
Yes it does, I didn’t have a chance to run it before merging on the CI, I can see many failures. Reverting

**Comment by muellerzr** [comment]
I’ll look at trying to do an alternative today

**Comment by jiqing-feng** [comment]
I know why it failed.... The best way is to return in each branch. I will update a another PR to fix it quickly. Sorry for the inconvinient.

**Comment by muellerzr** [comment]
No worries @jiqing-feng :) Lots of moving parts. 

I'll make sure to test it locally next time as well to make sure non-multi-cpu's don't break

**Pull request merged**
