### PR TITLE
[Utils] `has_offloaded_params`

### PR DESCRIPTION
**Pull request by kylesayrs**
## Purpose ##
* Add a `has_offloaded_params` utility function which returns `True` iff there is an `AlignDevicesHook` with offloading enabled
* Prepare for other utility functions to be implemented in future PRs

## Changes ##
* Implement utility function in `accelerate.utils.modeling`, exposed through `accelerate.utils`
* Replace repeat code use in `accelerate.utils.modeling` and `accelerate.accelerator` with newly added function

## Testing ##

<details><summary>test_has_offloaded_params.py</summary>

```python3
import torch

from accelerate.utils import has_offloaded_params
from accelerate.hooks import attach_align_device_hook
from accelerate.big_modeling import cpu_offload_with_hook

class ModelForTest(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = torch.nn.Linear(3, 4)
        self.batchnorm = torch.nn.BatchNorm1d(4)
        self.linear2 = torch.nn.Linear(4, 5)

    def forward(self, x):
        return self.linear2(self.batchnorm(self.linear1(x)))
    
model = ModelForTest()
assert not has_offloaded_params(model.linear1)
assert not has_offloaded_params(model.batchnorm)
assert not has_offloaded_params(model.batchnorm)

model = ModelForTest()
model, hook = cpu_offload_with_hook(model, execution_device="cuda:0")
assert not has_offloaded_params(model.linear1)
assert not has_offloaded_params(model.batchnorm)
assert not has_offloaded_params(model.batchnorm)

model = ModelForTest()
attach_align_device_hook(model, offload=False)
assert not has_offloaded_params(model.linear1)
assert not has_offloaded_params(model.batchnorm)
assert not has_offloaded_params(model.batchnorm)

model = ModelForTest()
attach_align_device_hook(model, offload=True)
assert has_offloaded_params(model.linear1)
assert has_offloaded_params(model.batchnorm)
assert has_offloaded_params(model.batchnorm)
```

</details>

## Who can review?
@SunMarc
@LysandreJik 
@mgoin

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Nice! Seems like a handy util :) 

Let's add it to `docs/source/package_references/big_modeling.md` ([`utils.modeling.has_offloaded_params`]) that way it's documented! :)

**Comment by muellerzr** [comment]
For the quality check, `pip install -e .[quality]; make style; make quality` should fix it right up!

**Comment by kylesayrs** [comment]
@SunMarc @muellerzr Thanks for the reviews! I've made some final changes, this is good to go from my end

**Comment by SunMarc** [comment]
I saw that you added some test in the PR description. Could you also add them in accelerate ? Thanks a lot !

**Comment by kylesayrs** [comment]
@SunMarc Added!

**Review by mgoin — COMMENTED** [review]
Nice integration Kyle!

**Pull request merged**
