### PR TITLE
Allowing encoded configuration for DeepSpeed

### PR DESCRIPTION
**Pull request by cli99**
DeepSpeed now allows deespeed configuration passed in as a base64 encoded string. This PR updates the check in accelerate to accommodate that change.

### CODE REVIEW

**Review by pacman100 — COMMENTED** [review]
Thank you for adding this 🤗! LGTM. Please resolve the quality checks and then we are good to go.

**Comment by pacman100** [comment]
Please do `pip install -e .[quality]` and `make style; make quality;` from the root of the repo to pass the quality failure

**Review by pacman100 — APPROVED** [review]
Hello, thank you for the changes. LGTM! 🤗

**Review by sgugger — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
