### PR TITLE
Fixes a few Sagemaker config issues

### PR DESCRIPTION
**Pull request by nroggendorff**
Updates config_args.py to work with the latest version of amazon sagemaker

In this new version, you are required to run variables operations with True or False, like `--do_eval True` as apposed to just `--do_eval`

### CODE REVIEW

**Comment by nroggendorff** [comment]
wdym 0 tests passed

**Comment by BenjaminBossan** [comment]
> is_local_machine = yaml.safe_load(f).get("compute_environment", ComputeEnvironment.LOCAL_MACHINE) == ComputeEnvironment.LOCAL_MACHINE

https://github.com/huggingface/accelerate/pull/2732/files#diff-a9f583abbef3c8f66fac00f7194fd0c4ff7e8744e6b5aea39bf61342984e3887R28

`f` is undefined, which is why the tests are failing.

**Comment by nroggendorff** [comment]
> > is_local_machine = yaml.safe_load(f).get("compute_environment", ComputeEnvironment.LOCAL_MACHINE) == ComputeEnvironment.LOCAL_MACHINE
> 
> https://github.com/huggingface/accelerate/pull/2732/files#diff-a9f583abbef3c8f66fac00f7194fd0c4ff7e8744e6b5aea39bf61342984e3887R28
> 
> `f` is undefined, which is why the tests are failing.

I see

**Comment by nroggendorff** [comment]
stupid mistake

**Comment by nroggendorff** [comment]
well, Idk what to do

**Comment by BenjaminBossan** [comment]
You're trying to use `is_local_machine` inside of `from_yaml_file`, where it's not defined, resulting in an error.

Generally, when CI fails, you can click on "Details" and check the failing tests there, this should give you an indication of what went wrong.

**Pull request closed without merging**
