### PR TITLE
Remove asking xpu plugin for non xpu devices

### PR DESCRIPTION
**Pull request by abhilash1910**
This PR removes asking for XPU plugin when user does not choose xpu devices .
@sgugger @muellerzr

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks! Can you run `make style` on your branch quickly for the formatting?

**Comment by abhilash1910** [comment]
Thanks for the review. @sgugger  I have a question regarding deepspeed integration, for now deepspeed supports the cuda case with nccl backend ; is there any plan to support ccl backend with deepspeed (for multi_xpu)? We are working with deepspeed to abstract xpu interface ; for accelerate this would be minimal change . (I have the changes and can create PR if reqd)

**Comment by sgugger** [comment]
cc @pacman100 who would know better than me :-)

**Comment by abhilash1910** [comment]
Thanks I will raise a separate discussion thread on this. Meanwhile @muellerzr  let me know if changes are ok?

**Review by muellerzr — APPROVED** [review]
Thanks!

**Pull request merged**
