### PR TITLE
fix crash when ipex is installed and torch has no xpu

### PR DESCRIPTION
**Pull request by sywangyi**
also when cpu flag is set. should use cpu instead of XPU

### CODE REVIEW

**Comment by sywangyi** [comment]
@sgugger

**Comment by sywangyi** [comment]
@abhilash1910  @muellerzr please help review

**Review by abhilash1910 — APPROVED** [review]
LGTM . cc @muellerzr for a second look

**Review by sgugger — APPROVED** [review]
Thanks for the fix! @muellerzr I'll let you mere if you're happy with the changes.

**Pull request merged**
