### PR TITLE
Sync states for xpu fsdp

### PR DESCRIPTION
**Pull request by abhilash1910**
Adds sync state for fsdp loading on rank 0 -> broadcasted to other xpu ranks. 
Links to #1777 
cc @pacman100 @muellerzr

### CODE REVIEW

**Review by pacman100 — APPROVED** [review]
Thank you @abhilash1910 for adding this, LGTM!

**Comment by pacman100** [comment]
cc @muellerzr  and @BenjaminBossan

**Review by BenjaminBossan — APPROVED** [review]
Yes, looks good, thanks.

**Review by muellerzr — APPROVED** [review]
Thanks! Just a general comment for future-proofing any more changes

**Comment by abhilash1910** [comment]
@muellerzr  could you re-review? Thanks.

**Comment by muellerzr** [comment]
Thanks!

**Pull request merged**
