### PR TITLE
add usage guide for ipex plugin

### PR DESCRIPTION
**Pull request by sywangyi**

### CODE REVIEW

**Comment by sywangyi** [comment]
@pacman100 @sgugger @yao-matrix @jianan-gu

**Review by sgugger — APPROVED** [review]
Thanks for adding this!

**Comment by sywangyi** [comment]
@pacman100 could you help review the doc？ thanks

**Review by pacman100 — COMMENTED** [review]
Hello @sywangyi, thank you for adding the usage guide, the part explaining distributed CPU training is very insightful! 🤗

**Pull request merged**
