### PR TITLE
delete CCL env var setting

### PR DESCRIPTION
**Pull request by Liangliang-Ma**
This PR deletes some CCL environment variable setting. With versions updating of software stack, current torch-CCL don't recommend manually setting these CCL env vars like 'CCL_LOCAL_SIZE', 'CCL_LOCAL_RANK' or 'CCL_PROCESS_LAUNCHER'.

And  `os.environ.get("LOCAL_WORLD_SIZE", "1")
os.environ.get("LOCAL_RANK", "0")`
may not get the correct value. For example, when run fine-tuning with deepspeed on multiple gpus, it will get wrong value and pass them to torchCCL comm backend, which will result in crash.

### CODE REVIEW

**Comment by Liangliang-Ma** [comment]
@muellerzr @faaany pls help to review. Thanks!

**Comment by faaany** [comment]
yes, I can verify that multi-card fine-tuning works without these CCL environment variables using the latest torch-ccl&ipex. They were added at a time when users had to handle them manually. But now we can remove them. Pls have a review, thx! @muellerzr

**Comment by faaany** [comment]
@yao-matrix

**Review by muellerzr — APPROVED** [review]
Thanks for the cleanup!

**Comment by muellerzr** [comment]
Can you run `make style; make quality`? (Don't worry about the import test)

**Comment by Liangliang-Ma** [comment]
@muellerzr Thanks. Format fixed.

**Pull request merged**
