### PR TITLE
fixed ip address typo

### PR DESCRIPTION
**Pull request by Fluder-Paradyne**
# What does this PR do?
Just fixed a typo in localhost ip address

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?

### CODE REVIEW

**Comment by Fluder-Paradyne** [comment]
Hi @sgugger, there was a typo in the example and the debug launcher

**Comment by BenjaminBossan** [comment]
Thanks for the fixes. Any specific reason why you closed #2094 and opened a new PR?

**Comment by Fluder-Paradyne** [comment]
it had 2 commits, first I saw this typo only in example file, later when I did global search, it was in 2 places
and in contributor guideline it said not to open any pr from fork repo's main branch

**Review by BenjaminBossan — APPROVED** [review]
Thanks for fixing the IP.

Depending on how IP resolution is implemented, it may not be necessary, e.g.:

```
$ ping 127.0.01
PING 127.0.01 (127.0.0.1) 56(84) bytes of data.
```

but the change shouldn't harm.

**Review by muellerzr — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
