### PR TITLE
Fix mpi4py/failing deepspeed test issues

### PR DESCRIPTION
**Pull request by muellerzr**
# What does this PR do?

Solves the issue of https://github.com/huggingface/accelerate/pull/2350, `mpi4py` needed to be `conda installed` in the image, so this PR updates the docker image to do so (since currently we don't have docker images sanctioned by subject and it's just one with everything)

You can see it passing here: https://github.com/huggingface/accelerate/actions/runs/7571310090

Fixes # (issue)

Failing nightly test

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@pacman100 @SunMarc

### CODE REVIEW

**Review by SunMarc — APPROVED** [review]
Thanks for fixing this ! Why do we need `conda install` ? It is possible to do a` pip install `? I don't like mixing pip and conda. However, I think it is fine as long as you use pip after conda. See related [doc](https://www.anaconda.com/blog/using-pip-in-a-conda-environment).

**Comment by muellerzr** [comment]
@SunMarc it's a very specific `mpi4py` thing because the `conda install` will get some needed compilation dependencies while `pip` does not. Sourab and I had to find this out the hard way a number of times 😓

**Comment by muellerzr** [comment]
We also do `conda install pip` so that way pip envs are stuck in the conda env it was made in

**Review by pacman100 — APPROVED** [review]
Thank you @muellerzr for fixing this difficult to debug issue, great investigation.

**Pull request merged**
