### PR TITLE
eliminate dead code

### PR DESCRIPTION
**Pull request by statelesshz**
# What does this PR do?

I noticed that the minimum version of `safetensors` that `accelerate` depends on is `0.4.3` https://github.com/huggingface/accelerate/blob/ba7ab93f5e688466ea56908ea3b056fae2f9a023/setup.py#L80

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

cc @muellerzr

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Thanks for the cleanup!

**Comment by BenjaminBossan** [comment]
@statelesshz The linter is complaining because the `compare_versions` is now obsolete. Could you please remove it?

**Comment by statelesshz** [comment]
cc @BenjaminBossan

**Comment by statelesshz** [comment]
> @statelesshz The linter is complaining because the `compare_versions` is now obsolete. Could you please remove it?

done :) cc @BenjaminBossan

**Comment by statelesshz** [comment]
I think this PR is ready to be merged :) @muellerzr

**Pull request merged**
