### PR TITLE
Allow custom SageMaker Estimator arguments

### PR DESCRIPTION
**Pull request by dennisbappert**
The current implementation for SageMaker only allows a limited set of arguments, however the `Estimator` and `HuggingFace` Estimator support many additional arguments. With the current config wizard, this would be very hard to implement, hence I added a new field to `SageMakerConfig` to allow overrides to be set.

This e.g. allows the usage of Spot Instances.

### CODE REVIEW

**Comment by pacman100** [comment]
Hello @dennisbappert, how will user specify `additional_args` as I don't see it being part of the `accelerate config` questionarrie ?

**Comment by dennisbappert** [comment]
I purposefully kept it out of the questionnaire, as it might be hard to enter in an interactive console session. It is mentioned in the documentation and for more advanced use-cases. I can add a hint in the questionnaire to guide the user towards the documentation. 

Do you think it will be valuable as an interactive input?

**Comment by dennisbappert** [comment]
Yes it has to be added directly. I modified the docs to include an example for Spot Instances, let me make that a bit more clear in the docs.

**Comment by sgugger** [comment]
cc @philschmid

**Comment by dennisbappert** [comment]
see ^^^

**Review by philschmid — APPROVED** [review]
LGTM! Good idea on adding more configurations

**Comment by dennisbappert** [comment]
I'm working on some more configuration right now: adding custom docker container support (Dockerfile in the repository), enhancing the documentation to cover local mode (which works fine, would just be nice as part of the documentation).

**Review by sgugger — APPROVED** [review]
LGTM, please ping us when you're happy with the documentation you're adding :-)

**Comment by dennisbappert** [comment]
You can merge this one, I will create additional PRs for the other changes.

**Pull request merged**
