### PR TITLE
Simplify CLI args validation and ensure CLI args take precedence over config file.

### PR DESCRIPTION
**Pull request by Iain-S**
# What does this PR do?

- We simplify the processsing of config file sub-sections (e.g. fsdp, megatron, ipex, deepspeed, etc). Previously, any time a dict was encountered in a config, all dicts in the config were re-processed. 
- CLI options such as --megatron_some_option will no longer be overridden by config options (there was previously no `if getattr(args, name, None)` check before overwriting the `arg.name`). It makes things more consistent but note that it does change existing behaviour.

## Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [x] Did you write any new necessary tests?

## Issues

Somewhat related to #2731.

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@muellerzr

## Notes for Reviewers

I've made the logic in `_validate_launch_command()` more explicit as the proposed

```python
    if args.config_file is not None or (os.path.isfile(default_config_file) and not args.cpu):
```

is equivalent to the previous

```python
    if args.config_file is not None or os.path.isfile(default_config_file) and not args.cpu:
```

However, if what we really want is

```python
    if (args.config_file is not None or os.path.isfile(default_config_file)) and not args.cpu:
```

then I'll happily edit but note that it would be changing the existing behaviour.

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Nice refactor and tests! Thanks for doing this 🤗

**Comment by muellerzr** [comment]
FYI this broke FSDP as defaults for that are not always `None`. Making a follow-up

**Comment by Iain-S** [comment]
Let me know if I need to resubmit this PR. If you could suggest a test case to catch the problem you found, that would be great.

**Comment by cyr0930** [comment]
hmm priority looks very messy

**Pull request merged**
