### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by stas00**
fixing a small typo

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Thanks Stas!

**Comment by muellerzr** [comment]
@stas00 can you do `pip install -e .[quality]; make style; make quality`? Thanks!

**Comment by stas00** [comment]
Yes, of course, Done.

On this project the CI doesn't get run on user's contributions until you allow it - so the contributor has no way of seeing their submission passes CI or not, resulting in prolonged processes.

**Comment by muellerzr** [comment]
Agreed, it should just be for first time contributors though

**Comment by stas00** [comment]
I was just about to ask if such settings is possible on github.

**Pull request merged**
