### PR TITLE
A bug Update dataclasses.py

### PR DESCRIPTION
**Pull request by wangpengfei1013**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by muellerzr — CHANGES_REQUESTED** [review]
It is meant to be upper, where in the codebase did it hint it should be lower? :)

**Comment by muellerzr** [comment]
(As if there's somewhere breaking it has that, it needs to be fixed)

**Comment by wangpengfei1013** [comment]
When I using the initial code
```
root@d6f55527739f:/workspace/sa/LLM_test/FastChat# bash run_yuan_fp8_test.sh
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2024-01-19 00:25:33,433] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)

Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.36it/s]Traceback (most recent call last):
  File "/workspace/sa/LLM_test/FastChat/fastchat/train/train_yuan_fp8.py", line 199, in <module>
    train()
  File "/workspace/sa/LLM_test/FastChat/fastchat/train/train_yuan_fp8.py", line 93, in train
    kwargs = FP8RecipeKwargs(backend="msamp", opt_level="O1")
  File "<string>", line 11, in __init__
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/dataclasses.py", line 248, in __post_init__
    raise ValueError("`backend` must be 'MSAMP' or 'TE' (TransformerEngine).")
ValueError: `backend` must be 'MSAMP' or 'TE' (TransformerEngine).
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1023, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 643, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'fastchat/train/train_yuan_fp8.py', '--model_name_or_path', '../LLM_models/yuan2-2B/', '--trust_remote_code', 'True', '--data_path', './data/multiturn_chat_faststyle_0.8M.json', '--bf16', 'True', '--output_dir', './checkpoints_yuan2_2b', '--lazy_preprocess', 'True', '--gradient_checkpointing', 'True']' returned non-zero exit status 1
```

vim /usr/local/lib/python3.10/dist-packages/accelerate/utils/dataclasses.py +248
update upper to lower, it did work
```
root@d6f55527739f:/workspace/sa/LLM_test/FastChat# vim /usr/local/lib/python3.10/dist-packages/accelerate/utils/dataclasses.py +248
root@d6f55527739f:/workspace/sa/LLM_test/FastChat# bash run_yuan_fp8_test.sh
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2024-01-19 00:28:13,713] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.38it/s]
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
  0%|                                                                                                                                                              | 0/53818 [00:00<?, ?it/s]
```

**Comment by muellerzr** [comment]
Thanks for the explanation! Wound up going with https://github.com/huggingface/accelerate/pull/2355

**Pull request closed without merging**
