### PR TITLE
Accelerate + Animus/Catalyst = 🚀 

### PR DESCRIPTION
**Pull request by Scitator**
Hi guys, nice project!

After recent experiments with accelerate, I found it very close to my own "torch-backend" ideas, so... I decided to move a couple of frameworks to accelerate.

tl;dr
- Catalyst is based on Accelerate starting from [v22 edition](https://github.com/catalyst-team/catalyst/releases/tag/v22.02rc0)
- Animus - from [v0.0.1](https://github.com/Scitator/animus)
- Animus & Catalyst added to readme/frameworks section
- frameworks sorted alphabetically (it's easier to navigate)

✌️

### CODE REVIEW

**Comment by Scitator** [comment]
btw, it would be great if you could comment on my "Accelerator mixin" - [Engine](https://github.com/Scitator/animus/blob/main/animus/torch/engine.py) in terms of "a bit more user-friendly Accelerator API". I found it useful for me to run pipelines within notebooks or python scripts without CLI.

**Comment by sgugger** [comment]
Ah thanks! I am wrapping up some things in Transformers and will go back to Accelerate pretty soon (haven't forgotten #215 !)

You mixins look great! Having one per kind of distributed setup is a bit against the philosophy of Accelerate (where the same exact code runs on any setup) but I like the abstraction.

To run things in notebooks, we also have `notebook_launcher`, I don't know if you tried it or not.

**Comment by Scitator** [comment]
yeah, I found `notebook_launcher` an interesting functional alternative... nevertheless, from previous experience I knew a few limitations of pure functional way, so... a small class-based API was created ;)

**Review by sgugger — APPROVED** [review]
Sorry I read this as an issue and not a PR 🤦‍♂️

**Pull request merged**
