### PR TITLE
make deepspeed optimizer match parameters of passed optimizer

### PR DESCRIPTION
**Pull request by jmhessel**
I am trying to do some prompt tuning with deepspeed+accelerate, and by default, when using deepspeed, all model parameters are updated. Instead, I'd like to only update the ones that I put in the original optimizer.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for fixing!

**Comment by sgugger** [comment]
Could you just run `make style` on your branch to fix the quality issue? Thanks!

**Comment by jmhessel** [comment]
is this okay? it looks like there are a few other lines in there that also got style fixed

**Comment by sgugger** [comment]
Looks good, thanks again!

**Pull request merged**
