### PR TITLE
enable cpu bnb distributed lora finetune

### PR DESCRIPTION
**Pull request by jiqing-feng**
Hi @SunMarc , this PR enables cpu bnb model distributed finetune by removing check index because we don't need index in cpu device. Please review it. Thanks!

### CODE REVIEW

**Comment by jiqing-feng** [comment]
Hi @SunMarc @ArthurZucker  , if we don't make this change, the error be like:
image

**Review by SunMarc — COMMENTED** [review]
Thanks for the PR @jiqing-feng ! Instead of removing this check, could you add the multi-backend bnb check ?

**Comment by jiqing-feng** [comment]
Hi @SunMarc . I have checked bnb multi-backend, please review it. Thx!

**Review by SunMarc — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
