### PR TITLE
Add in code exploration tool to docs

### PR DESCRIPTION
**Pull request by muellerzr**
This PR introduces an interactive feature integrator tool into the Accelerate documentation. The space itself is hosted [here](https://huggingface.co/spaces/muellerzr/accelerate_examples). It operates by first having the user select a feature:

image

Then it will provide them with the code diff, an explanation, and a link to the docs for more information:

image

Ideally we use this for all of the items that exist in "Usage Guides" as fast visual tutorials, before linking to others. In the future this would include having an option to view CLI options as well as Big Model Inference, and other items with higher complexity's/diffs in a seperate interface category users can use (like select "Accelerator" vs "CLI" vs "Big Model Inference")

To add a new tutorial, please see the [README](https://huggingface.co/spaces/muellerzr/accelerate_examples/blob/main/README.md) on the space, or request I make one for you 😉 

Preview on the docs at: https://moon-ci-docs.huggingface.co/docs/accelerate/pr_1014/en/usage_guides/explore

### CODE REVIEW

**Comment by sgugger** [comment]
In the preview, we can't really see anything with the tiny window :-(

**Comment by muellerzr** [comment]
@sgugger please try again :)

**Review by sgugger — APPROVED** [review]
Nice!

**Review by pacman100 — APPROVED** [review]
Awesome! 🚀

**Pull request merged**
