### PR TITLE
Adding `requires_grad` to `kwargs` when registering empty parameters.

### LINKED ISSUE #2361: `requires_grad` is not properly extracted when registering empty parameters.
```python
def register_empty_parameter(module, name, param):
    old_register_parameter(module, name, param)
    if param is not None:
        param_cls = type(module._parameters[name])
        kwargs = module._parameters[name].__dict__
        module._parameters[name] = param_cls(module._parameters[name].to(device), **kwargs)
```

In `register_empty_parameter`, both the original parameter `module._parameters[name]` and the new parameter `param` don't require grad in my case of `int16` parameters. However, the newly created `param_cls(module._parameters[name].to(device), **kwargs)` ([here](https://github.com/huggingface/accelerate/blob/5ec00da2befbe9fa666f1bee8bdb1dd4daf713e3/src/accelerate/big_modeling.py#L126C22-L126C45)) parameter requires grad anyway, because `requires_grad=False` doesn't make it into `kwargs` for some reason. But since it's integer, it can't require grad and the whole thing fails.

Example notebook: [colab](https://colab.research.google.com/drive/1IwAAKmj9aGaM2N_MKzmyZNYuPemjVEeR?usp=sharing)

### PR DESCRIPTION
**Pull request by BlackSamorez**
# What does this PR do?

Fixes #2361 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Thanks @BlackSamorez , in princple this looks ok. I just have a small doubt on whether this could affect transformers + bnb integration. Could you run the 4-bit tests on transformers? `RUN_SLOW=1 pytest tests/quantization/bnb/test_4bit.py`. Otherwise I can do it for you and report the results here

**Comment by BlackSamorez** [comment]
@younesbelkada  Looks like no problems there:
```
CUDA_VISIBLE_DEVICES=7 RUN_SLOW=1 pytest tests/quantization/bnb/test_4bit.py
==================================================================================================================================== test session starts =====================================================================================================================================
platform linux -- Python 3.11.5, pytest-7.4.4, pluggy-1.4.0
rootdir: /home/blacksamorez/transformers
configfile: pyproject.toml
plugins: anyio-3.7.1
collected 37 items                                                                                                                                                                                                                                                                           

tests/quantization/bnb/test_4bit.py ..............s......................                                                                                                                                                                                                              [100%]

====================================================================================================================================== warnings summary ======================================================================================================================================
../quip-sharp/.conda/lib/python3.11/site-packages/_pytest/config/__init__.py:1373
  /home/blacksamorez/quip-sharp/.conda/lib/python3.11/site-packages/_pytest/config/__init__.py:1373: PytestConfigWarning: Unknown config option: doctest_glob
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

tests/quantization/bnb/test_4bit.py: 10 warnings
  /home/blacksamorez/quip-sharp/.conda/lib/python3.11/site-packages/bitsandbytes/nn/modules.py:226: UserWarning: Input type into Linear4bit is torch.float16, but bnb_4bit_compute_dtype=torch.float32 (default). This will lead to slow inference or training speed.
    warnings.warn(f'Input type into Linear4bit is torch.float16, but bnb_4bit_compute_dtype=torch.float32 (default). This will lead to slow inference or training speed.')

tests/quantization/bnb/test_4bit.py::Bnb4BitTest::test_rwkv_4bit
  /home/blacksamorez/quip-sharp/.conda/lib/python3.11/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
    return self.fget.__get__(instance, owner)()

tests/quantization/bnb/test_4bit.py::Bnb4BitTest::test_rwkv_4bit
  /home/blacksamorez/quip-sharp/.conda/lib/python3.11/site-packages/torch/utils/cpp_extension.py:28: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import packaging  # type: ignore[attr-defined]

tests/quantization/bnb/test_4bit.py::Bnb4BitT5Test::test_inference_with_keep_in_fp32
tests/quantization/bnb/test_4bit.py::Bnb4BitT5Test::test_inference_with_keep_in_fp32
tests/quantization/bnb/test_4bit.py::Bnb4BitT5Test::test_inference_without_keep_in_fp32
tests/quantization/bnb/test_4bit.py::Bnb4BitT5Test::test_inference_without_keep_in_fp32
  /home/blacksamorez/transformers/src/transformers/generation/utils.py:1133: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
    warnings.warn(

tests/quantization/bnb/test_4bit.py::Bnb4BitT5Test::test_inference_with_keep_in_fp32
tests/quantization/bnb/test_4bit.py::Bnb4BitT5Test::test_inference_without_keep_in_fp32
  /home/blacksamorez/quip-sharp/.conda/lib/python3.11/site-packages/bitsandbytes/nn/modules.py:223: UserWarning: Input type into Linear4bit is torch.float16, but bnb_4bit_compute_dtype=torch.float32 (default). This will lead to slow inference.
    warnings.warn(f'Input type into Linear4bit is torch.float16, but bnb_4bit_compute_dtype=torch.float32 (default). This will lead to slow inference.')

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=================================================================================================================== 36 passed, 1 skipped, 19 warnings in 344.18s (0:05:44) ===================================================================================================================
```

Setup:
```
Name: accelerate
Version: 0.27.0.dev0
Summary: Accelerate
Home-page: https://github.com/huggingface/accelerate
Author: The HuggingFace team
Author-email: sylvain@huggingface.co
License: Apache
Location: /home/blacksamorez/quip-sharp/.conda/lib/python3.11/site-packages
Editable project location: /home/blacksamorez/accelerate
Requires: huggingface-hub, numpy, packaging, psutil, pyyaml, safetensors, torch
Required-by: 
---
Name: transformers
Version: 4.38.0.dev0
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /home/blacksamorez/quip-sharp/.conda/lib/python3.11/site-packages
Editable project location: /home/blacksamorez/transformers
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: lm-eval
---
Name: bitsandbytes
Version: 0.42.0
Summary: k-bit optimizers and matrix multiplication routines.
Home-page: https://github.com/TimDettmers/bitsandbytes
Author: Tim Dettmers
Author-email: dettmers@cs.washington.edu
License: MIT
Location: /home/blacksamorez/quip-sharp/.conda/lib/python3.11/site-packages
Requires: scipy
Required-by: 
```

**Review by younesbelkada — APPROVED** [review]
Looks great, thanks so much @BlackSamorez !

**Review by muellerzr — APPROVED** [review]
Thanks!

**Pull request merged**
