### PR TITLE
fix the fsdp docs

### PR DESCRIPTION
**Pull request by pacman100**
# What does this PR do?
1. Fixes https://github.com/huggingface/accelerate/issues/1943

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Thanks for the quick fix!

**Comment by hamelsmu** [comment]
How do you figure out the right value for this config?  Let's say for other models.  Sorry for the dumb question!  Any tips appreciated (maybe put that in the docs too?)

**Review by BenjaminBossan — APPROVED** [review]
Thanks for the fix, LGTM

**Comment by pacman100** [comment]
Hello @hamelsmu ,

> How do you figure out the right value for this config? Let's say for other models. Sorry for the dumb question! Any tips appreciated (maybe put that in the docs too?)

It is mentioned in the docs for transformers here https://huggingface.co/docs/transformers/main_classes/trainer#pytorch-fully-sharded-data-parallel, will raise a PR to have those in Accelerate. Specifically the below point:

> For transformer based auto wrap policy, it is recommended to specify `fsdp_transformer_layer_cls_to_wrap` in the config file. If not specified, the default value is `model._no_split_modules` when available. This specifies the list of transformer layer class name (case-sensitive) to wrap ,e.g, BertLayer, GPTJBlock, T5Block … This is important because submodules that share weights (e.g., embedding layer) should not end up in different FSDP wrapped units. Using this policy, wrapping happens for each block containing Multi-Head Attention followed by couple of MLP layers. Remaining layers including the shared embeddings are conveniently wrapped in same outermost FSDP unit. Therefore, use this for transformer based models.

**Pull request merged**
