### PR TITLE
[don't merge yet] unpin torch

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

Revert #2394 as torch 2.2 (with corresponding torchvision/torchaudio) works now in `transformers` and we will unpin those - however, this requires `accelerate` to unpin too) 🙏

### CODE REVIEW

**Comment by muellerzr** [comment]
@SunMarc is still working on a number of failures with torch 2.2, big modeling isn’t a fan of it :)

**Comment by ydshieh** [comment]
You mean some `accelerate` tests right? OK `transformers` can wait too

**Comment by muellerzr** [comment]
Yes

**Review by muellerzr — APPROVED** [review]
Marc confirmed on the DGX torch 2.2 all tests passed, failures on our runner is *unrelated*

**Pull request merged**
